Repository woowacourse-teams/2021-jujeol-jujeol, pull requests merged in 2021-08, with the labels that each got.

#191 fix: 내가 마신 술의 선호도 실제값으로 수정
  backend/src/main/java/com/jujeol/member/application/MemberService.java
  backend/src/main/java/com/jujeol/member/domain/PreferenceRepository.java
  backend/src/test/java/com/jujeol/member/acceptance/MemberInfoAcceptanceTest.java
  backend/src/test/java/com/jujeol/member/domain/MemberInfoRepositoryTest.java
Labels: 🐞 버그, 🔥 백엔드, 🕹 기능

#190 feat: 검색 기능 구현과 카테고리 조회 기능 구현
  backend/build.gradle
  backend/src/main/java/com/jujeol/admin/ui/AdminController.java
  backend/src/main/java/com/jujeol/commons/config/QuerydslConfiguration.java
  backend/src/main/java/com/jujeol/drink/application/DrinkService.java
  backend/src/main/java/com/jujeol/drink/application/dto/SearchDto.java
  backend/src/main/java/com/jujeol/drink/domain/RecommendationTheme.java
  backend/src/main/java/com/jujeol/drink/domain/Search.java
  backend/src/main/java/com/jujeol/drink/domain/repository/DrinkCustomRepository.java
  backend/src/main/java/com/jujeol/drink/domain/repository/DrinkRepository.java
  backend/src/main/java/com/jujeol/drink/domain/repository/DrinkRepositoryImpl.java
  backend/src/main/java/com/jujeol/drink/ui/CategoryController.java
  backend/src/main/java/com/jujeol/drink/ui/DrinkController.java
  backend/src/main/java/com/jujeol/drink/ui/dto/SearchRequest.java
  backend/src/main/java/com/jujeol/member/application/MemberService.java
  backend/src/main/java/com/jujeol/member/domain/Preference.java
  backend/src/test/java/com/jujeol/JujeolApplicationTest.java
  backend/src/test/java/com/jujeol/TestConfig.java
  backend/src/test/java/com/jujeol/drink/DrinkTestContainer.java
  backend/src/test/java/com/jujeol/drink/acceptance/DrinkAcceptanceTest.java
  backend/src/test/java/com/jujeol/drink/domain/repository/DrinkRepositoryTest.java
  backend/src/test/java/com/jujeol/drink/domain/repository/ReviewRepositoryTest.java
  backend/src/test/java/com/jujeol/member/domain/MemberInfoRepositoryTest.java
  backend/src/test/java/com/jujeol/member/domain/MemberRepositoryTest.java
  backend/src/test/java/com/jujeol/member/domain/PreferenceRepositoryTest.java
Labels: 🔥 백엔드, 🕹 기능

#198 feat: 기존 추천 알고리즘을 협업 필터링으로 변경
  backend/build.gradle
  backend/src/docs/asciidoc/index.adoc
  backend/src/main/java/com/jujeol/admin/ui/AdminController.java
  backend/src/main/java/com/jujeol/drink/application/DrinkService.java
  backend/src/main/java/com/jujeol/drink/domain/RecommendAnonymous.java
  backend/src/main/java/com/jujeol/drink/domain/RecommendFactory.java
  backend/src/main/java/com/jujeol/drink/domain/RecommendMember.java
  backend/src/main/java/com/jujeol/drink/domain/RecommendState.java
  backend/src/main/java/com/jujeol/drink/domain/repository/DrinkRepository.java
  backend/src/main/java/com/jujeol/drink/infrastructure/recommend/H2RecommendationDataModel.java
  backend/src/main/java/com/jujeol/drink/infrastructure/recommend/RecommendationDataModel.java
  backend/src/main/java/com/jujeol/drink/infrastructure/recommend/RecommendationSystem.java
  backend/src/main/java/com/jujeol/drink/ui/DrinkController.java
  backend/src/main/java/com/jujeol/drink/ui/dto/CategoryResponse.java
  backend/src/main/java/com/jujeol/drink/ui/dto/SearchRequest.java
  backend/src/main/java/com/jujeol/member/ui/LoginMember.java
  backend/src/test/java/com/jujeol/admin/acceptance/AdminAcceptanceTool.java
  backend/src/test/java/com/jujeol/drink/DrinkTestContainer.java
  backend/src/test/java/com/jujeol/drink/acceptance/DrinkAcceptanceTest.java
  backend/src/test/java/com/jujeol/drink/domain/repository/ReviewRepositoryTest.java
  backend/src/test/java/com/jujeol/member/acceptance/MemberAcceptanceTest.java
  backend/src/test/java/com/jujeol/member/acceptance/MemberAcceptanceTool.java
Labels: 🔥 백엔드, 🕹 기능

#192 docs: api 문서 수정
  backend/src/docs/asciidoc/category.adoc
  backend/src/docs/asciidoc/drink.adoc
  backend/src/docs/asciidoc/error.adoc
  backend/src/docs/asciidoc/index.adoc
  backend/src/docs/asciidoc/login.adoc
  backend/src/docs/asciidoc/member.adoc
  backend/src/docs/asciidoc/preference.adoc
  backend/src/docs/asciidoc/review.adoc
Labels: 📋 문서, 🔥 백엔드

#202 feat: 프론트 배포 버튼 추가 및 aws s3 업로드 명령어 수정
  .github/workflows/front-dev-deploy.yml
  .github/workflows/front-prod-deploy.yml
Labels: 🏗인프라, 👩‍💻 프론트

#200 refactor: 협업 필터링에 달린 리뷰 반영
  backend/src/main/java/com/jujeol/drink/application/DrinkService.java
  backend/src/main/java/com/jujeol/drink/application/RecommendFactory.java
  backend/src/main/java/com/jujeol/drink/application/RecommendStrategy.java
  backend/src/main/java/com/jujeol/drink/domain/RecommendFactory.java
  backend/src/main/java/com/jujeol/drink/domain/RecommendForAnonymous.java
  backend/src/main/java/com/jujeol/drink/domain/RecommendForMember.java
  backend/src/main/java/com/jujeol/drink/domain/RecommendState.java
  backend/src/main/java/com/jujeol/drink/infrastructure/recommend/MySqlRecommendationDataModel.java
  backend/src/main/java/com/jujeol/drink/ui/DrinkController.java
Labels: 🔥 백엔드

#204 fix: 전체 카테고리 디비 등록 구현 (dev, local)
  backend/src/main/java/com/jujeol/DataLoader.java
Labels: 🔥 백엔드

#205 fix: 검색 단어의 대소문자 구분 없애는 기능 추가
  backend/src/main/java/com/jujeol/drink/domain/repository/DrinkRepositoryImpl.java
  backend/src/test/java/com/jujeol/drink/acceptance/DrinkAcceptanceTest.java
Labels: 🔥 백엔드, 🕹 기능

#212 fix: isExists 메서드를 queryDSL 구문으로 변경
  backend/src/main/java/com/jujeol/member/domain/MemberCustomRepository.java
  backend/src/main/java/com/jujeol/member/domain/MemberRepository.java
  backend/src/main/java/com/jujeol/member/domain/MemberRepositoryImpl.java
Labels: 🐞 버그, 🔥 백엔드, 🕹 기능

#213 fix: 추천 주류가 없을시 발생하는 문제 수정
  backend/src/main/java/com/jujeol/drink/domain/RecommendForMember.java
Labels: 🐞 버그, 🔥 백엔드

#214 fix: 리뷰 조회 시 500 에러 수정
  backend/src/main/java/com/jujeol/DataLoader.java
Labels: 🐞 버그, 🔥 백엔드

#215 fix: isExsits에 파라미터로 받은 nickname과 비교하는 where 구문으로 수정
  backend/src/main/java/com/jujeol/member/domain/MemberRepositoryImpl.java
Labels: 🐞 버그, 🔥 백엔드, 🕹 기능

#206 feat: 검색 기능 구현
  frontend/src/apis/requests.ts
  frontend/src/pages/SearchPage/index.tsx
  frontend/src/pages/SearchResultPage/index.tsx
  frontend/src/types.d.ts
Labels: 👩‍💻 프론트, 🕹 기능

#217 feat: dev에서 콘솔 로깅 추가
  backend/src/main/resources/application.yml
Labels: ⚙️ 설정⚒, 🔥 백엔드

#222 fix: 데이터로더 익명 유저 추가
  backend/src/main/java/com/jujeol/DataLoader.java
Labels: 🐞 버그, 🔥 백엔드

#224 refactor: 구글 애널리틱스 추가, API 변경사항 적용(추천, 리뷰), 마이페이지 리다이렉트 이슈 해결, 모바일 화면에서 모달 하단부분이 잘려보이는 이슈 해결
  frontend/public/index.html
  frontend/public/netlify.toml
  frontend/src/App.tsx
  frontend/src/GlobalStyle.tsx
  frontend/src/apis/requests.ts
  frontend/src/components/Card/ReviewCard.tsx
  frontend/src/constants/requestUrl.ts
  frontend/src/contexts/UserContext.tsx
  frontend/src/pages/HomePage/DrinkListSection.tsx
  frontend/src/pages/HomePage/config.ts
  frontend/src/pages/HomePage/index.tsx
  frontend/src/pages/HomePage/test.tsx
  frontend/src/pages/MyPage/index.tsx
  frontend/src/pages/ViewAllPage/index.tsx
  frontend/src/types.d.ts
Labels: 🐞 버그, 👩‍💻 프론트, 🕹 기능

#226 fix: Preference 테이블 소문자로 변경
  backend/src/main/java/com/jujeol/drink/infrastructure/recommend/H2RecommendationDataModel.java
  backend/src/main/java/com/jujeol/drink/infrastructure/recommend/MySqlRecommendationDataModel.java
  backend/src/main/java/com/jujeol/drink/infrastructure/recommend/RecommendationSystem.java
  backend/src/test/java/com/jujeol/drink/acceptance/DrinkAcceptanceTest.java
Labels: 🔥 백엔드

#229 fix: 여러번 날아가는 쿼리를 임시방편으로 EAGER 로 수정
  backend/src/main/java/com/jujeol/drink/domain/Drink.java
  backend/src/main/java/com/jujeol/drink/domain/Review.java
  backend/src/main/java/com/jujeol/drink/domain/ViewCount.java
  backend/src/main/java/com/jujeol/member/domain/Preference.java
Labels: 🔥 백엔드

#231 fix: 여러번 날아가는 쿼리를 Join Fetch로 수정 (n+1문제 해결)
  backend/src/main/java/com/jujeol/drink/application/DrinkService.java
  backend/src/main/java/com/jujeol/drink/application/ViewCountService.java
  backend/src/main/java/com/jujeol/drink/application/dto/DrinkDto.java
  backend/src/main/java/com/jujeol/drink/application/dto/DrinkRequestDto.java
  backend/src/main/java/com/jujeol/drink/domain/Drink.java
  backend/src/main/java/com/jujeol/drink/domain/RecommendForAnonymous.java
  backend/src/main/java/com/jujeol/drink/domain/ViewCount.java
  backend/src/main/java/com/jujeol/drink/domain/repository/DrinkRepository.java
  backend/src/main/java/com/jujeol/drink/domain/repository/DrinkRepositoryImpl.java
  backend/src/main/java/com/jujeol/drink/domain/repository/ReviewRepository.java
  backend/src/main/java/com/jujeol/drink/domain/repository/ViewCountRepository.java
  backend/src/main/java/com/jujeol/drink/ui/dto/DrinkDetailResponse.java
  backend/src/main/java/com/jujeol/member/application/MemberService.java
  backend/src/main/java/com/jujeol/member/domain/PreferenceRepository.java
  frontend/package-lock.json
Labels: 🐞 버그, 🔥 백엔드

#232 fix: ViewCount 테스트 삭제
  backend/src/test/java/com/jujeol/drink/domain/repository/DrinkRepositoryTest.java
Labels: 🔥 백엔드

#230 refactor: 헤더 로고에 배포 환경 표시 및 선호도 평균 소수점 둘 째 자리에서 반올림해서 화면에 표시하도록 변경
  frontend/env/.env.development
  frontend/env/.env.local
  frontend/env/.env.prod
  frontend/src/components/Header/MainHeader.styles.ts
  frontend/src/pages/DrinksDetailPage/index.tsx
Labels: 👩‍💻 프론트

#233 fix: query 튜닝
  backend/src/main/java/com/jujeol/drink/application/CategoryService.java
  backend/src/main/java/com/jujeol/drink/application/DrinkService.java
  backend/src/main/java/com/jujeol/drink/domain/repository/DrinkRepository.java
  backend/src/main/java/com/jujeol/member/application/MemberService.java
  backend/src/main/java/com/jujeol/member/domain/Member.java
  backend/src/main/java/com/jujeol/member/domain/Preference.java
  backend/src/main/java/com/jujeol/member/domain/PreferenceRepository.java
Labels: 🔥 백엔드

#234 feat: 1.0.0 베타 버전으로 버전 수정 및 README.md 업데이트
  README.md
  backend/build.gradle
  frontend/package.json
Labels: ⚙️ 설정⚒, 🏗인프라, 🕹 기능

#237 fix: github action 빌드 커맨드 수정
  .github/workflows/front-prod-deploy.yml
  backend/build.gradle
  frontend/package.json
Labels: 🏗인프라, 🐞 버그, 👩‍💻 프론트

#238 fix: oauth 에 redirect url 수정
  backend/build.gradle
  frontend/env/.env.prod
  frontend/package.json
Labels: 🏗인프라, 🐞 버그, 👩‍💻 프론트

#242 fix: hotfix를 develop에 머지
  .github/workflows/front-prod-deploy.yml
  backend/build.gradle
  frontend/env/.env.prod
  frontend/package.json
Labels: 🐞 버그, 👩‍💻 프론트, 🔥 백엔드

#241 fix: dataloader 잘 못된 데이터 수정
  backend/src/main/java/com/jujeol/DataLoader.java
Labels: 🐞 버그, 🔥 백엔드

#265 feat: aws Cloud front caching invalid(dev,prod) 설정
  .github/workflows/front-dev-deploy.yml
  .github/workflows/front-prod-deploy.yml
Labels: 🏗인프라, 👩‍💻 프론트

#259 feat: pr 시 테스트가 통과하는지 확인할 수 있는 workflow 추가
  .github/workflows/backend-build-test.yml
Labels: 🍻 테스트, 🔥 백엔드

#267 fix: timezone 관련 설정 추가
  backend/src/main/java/com/jujeol/JujeolApplication.java
Labels: ⚙️ 설정⚒, 🐞 버그, 🔥 백엔드

#263 fix: 무한 스크롤을 위한 observer 타겟 설정
  frontend/src/pages/MyDrinksPage/index.tsx
Labels: 🐞 버그, 👩‍💻 프론트

#268 refactor: tabBar 스타일 변경
  frontend/src/components/Tab/Tab.styles.ts
Labels: 👩‍💻 프론트, 📱 UI

#266 feat: 검색 기능 고도화
  backend/src/docs/asciidoc/drink.adoc
  backend/src/main/java/com/jujeol/drink/application/DrinkService.java
  backend/src/main/java/com/jujeol/drink/application/dto/SearchDto.java
  backend/src/main/java/com/jujeol/drink/domain/Search.java
  backend/src/main/java/com/jujeol/drink/domain/SearchWords.java
  backend/src/main/java/com/jujeol/drink/domain/repository/DrinkCustomRepository.java
  backend/src/main/java/com/jujeol/drink/domain/repository/DrinkRepositoryImpl.java
  backend/src/test/java/com/jujeol/drink/acceptance/DrinkAcceptanceTest.java
Labels: 🕹 기능, 🔥 백엔드

#279 refactor: DataModel 에서 여러번 쿼리 날아가는 것 수정
  backend/src/main/java/com/jujeol/drink/infrastructure/recommend/H2RecommendationDataModel.java
  backend/src/main/java/com/jujeol/drink/infrastructure/recommend/MemberPreference.java
  backend/src/main/java/com/jujeol/drink/infrastructure/recommend/MySqlRecommendationDataModel.java
  backend/src/main/java/com/jujeol/drink/infrastructure/recommend/PreferenceDataModel.java
  backend/src/main/java/com/jujeol/drink/infrastructure/recommend/RecommendationDataModel.java
  backend/src/main/java/com/jujeol/drink/infrastructure/recommend/RecommendationSystem.java
  backend/src/test/java/com/jujeol/drink/acceptance/DrinkAcceptanceTest.java
Labels: 🔥 백엔드, 🐞 버그

#281 feat: 쿼리 갯수를 세어주는 query spy 기능 구현
  backend/src/test/java/com/jujeol/testdatabase/Count.java
  backend/src/test/java/com/jujeol/testdatabase/DatabaseConfig.java
  backend/src/test/java/com/jujeol/testdatabase/LoggerPrinter.java
  backend/src/test/java/com/jujeol/testdatabase/ProxyConnectionHandler.java
  backend/src/test/java/com/jujeol/testdatabase/QueryCounter.java
  backend/src/test/java/com/jujeol/testdatabase/QueryLog.java
  backend/src/test/java/com/jujeol/testdatabase/QueryResult.java
  backend/src/test/java/com/jujeol/testdatabase/TestDataSource.java
Labels: 🔥 백엔드

#283 feat: 로그에 의미 있는 정보 출력 구현
  backend/build.gradle
  backend/src/main/java/com/jujeol/commons/aop/LogAop.java
  backend/src/main/java/com/jujeol/commons/aop/LogWithTime.java
  backend/src/main/java/com/jujeol/commons/config/P6spySqlFormatConfiguration.java
  backend/src/main/java/com/jujeol/commons/config/P6spySqlLogFormatter.java
  backend/src/main/java/com/jujeol/commons/config/WebMvcConfig.java
  backend/src/main/java/com/jujeol/commons/interceptor/LogInterceptor.java
  backend/src/main/java/com/jujeol/drink/application/DrinkService.java
  backend/src/main/java/com/jujeol/drink/application/RecommendFactory.java
  backend/src/main/java/com/jujeol/drink/ui/dto/MemberSimpleResponse.java
  backend/src/main/java/com/jujeol/member/application/LoginService.java
  backend/src/main/java/com/jujeol/member/application/MemberService.java
  backend/src/main/java/com/jujeol/member/application/dto/MemberDto.java
  backend/src/main/java/com/jujeol/member/application/dto/PreferenceDto.java
  backend/src/main/java/com/jujeol/member/application/dto/SocialProviderCodeDto.java
  backend/src/main/java/com/jujeol/member/application/dto/TokenDto.java
  backend/src/main/java/com/jujeol/member/config/AuthenticationPrincipalConfig.java
  backend/src/main/java/com/jujeol/member/ui/MemberController.java
  backend/src/main/java/com/jujeol/member/ui/dto/MemberDrinkResponse.java
  backend/src/main/java/com/jujeol/member/ui/dto/PreferenceResponse.java
  backend/src/main/java/com/jujeol/member/ui/dto/SocialProviderCodeRequest.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application-prod.yml
  backend/src/main/resources/application.yml
  backend/src/main/resources/logback-access.xml
  backend/src/main/resources/logback-spring.xml
  backend/src/test/java/com/jujeol/RequestBuilder.java
  backend/src/test/java/com/jujeol/member/acceptance/MemberAcceptanceTest.java
  backend/src/test/java/com/jujeol/member/acceptance/MemberAcceptanceTool.java
  backend/src/test/java/com/jujeol/member/fixture/TestMember.java
Labels: 🕹 기능, 🔥 백엔드

#299 fix: 이미 선호도를 등록한 주류는 추천 주류에서 제거
  backend/src/main/java/com/jujeol/drink/application/RecommendFactory.java
  backend/src/main/java/com/jujeol/drink/domain/RecommendForMember.java
  backend/src/main/java/com/jujeol/drink/domain/repository/DrinkRepository.java
  backend/src/test/java/com/jujeol/drink/acceptance/DrinkAcceptanceTest.java
Labels: 🔥 백엔드

#277 feat: 검색결과 없음 화면 구현
  frontend/src/apis/requests.ts
  frontend/src/components/@shared/SearchBar/SearchBar.tsx
  frontend/src/components/Card/PersonalReviewCard.styles.ts
  frontend/src/components/Card/PersonalReviewCard.tsx
  frontend/src/components/Card/ReviewCard.styles.ts
  frontend/src/components/Card/ReviewCard.tsx
  frontend/src/components/Item/CardItem.styles.ts
  frontend/src/components/Item/ListItem.styles.ts
  frontend/src/components/Item/PersonalReviewItem.tsx
  frontend/src/components/Item/VerticalItem.styles.ts
  frontend/src/components/List/CardList.styles.ts
  frontend/src/components/Review/ReviewCreateForm.tsx
  frontend/src/components/Review/ReviewEditForm.tsx
  frontend/src/constants/index.ts
  frontend/src/constants/search.ts
  frontend/src/pages/HomePage/DrinkListSection.tsx
  frontend/src/pages/MyDrinksPage/MyDrinkItem.styles.ts
  frontend/src/pages/MyDrinksPage/MyDrinkItem.tsx
  frontend/src/pages/MyDrinksPage/index.tsx
  frontend/src/pages/MyPage/index.tsx
  frontend/src/pages/SearchResultPage/NoSearchResult.styles.ts
  frontend/src/pages/SearchResultPage/NoSearchResults.tsx
  frontend/src/pages/SearchResultPage/index.tsx
  frontend/src/pages/SearchResultPage/styles.ts
  frontend/src/pages/ViewAllPage/index.tsx
  frontend/src/styles/Flex.ts
  frontend/src/styles/LineClamp.ts
  frontend/src/types.d.ts
Labels: 🕹 기능, 👩‍💻 프론트, 📱 UI

#284 feat: 모바일에서 모달 끌어서 닫기 기능 구현
  frontend/src/components/@shared/MeatBallsButton/MeatBallsButton.tsx
  frontend/src/components/Card/ReviewCard.tsx
  frontend/src/components/Modal/Modal.styles.ts
  frontend/src/components/Modal/Modal.tsx
Labels: 🕹 기능, 👩‍💻 프론트, 📱 UI

#286 feat: 상품 상세페이지 뒤로 가기 버튼 구현
  frontend/src/components/@shared/Arrow/Arrow.ts
  frontend/src/components/@shared/GoBackButton/GoBackButton.styles.ts
  frontend/src/components/@shared/GoBackButton/GoBackButton.tsx
  frontend/src/pages/DrinksDetailPage/index.tsx
  frontend/src/pages/DrinksDetailPage/styles.ts
Labels: 🕹 기능, 👩‍💻 프론트

#302 config: log 보관 최대 기간 변경
  backend/src/main/resources/logback-access.xml
  backend/src/main/resources/logback-spring.xml
Labels: ⚙️ 설정⚒, 🔥 백엔드, 🏗인프라

#297 fix: drinks 검색 시 페이지 오류 해결
  backend/src/main/java/com/jujeol/drink/application/DrinkService.java
Labels: 🔥 백엔드, 🐞 버그

#305 fix: 추천에 내가 마신 음료도 포함
  backend/src/main/java/com/jujeol/commons/aop/LogAop.java
  backend/src/main/java/com/jujeol/drink/application/RecommendFactory.java
  backend/src/main/java/com/jujeol/drink/domain/RecommendForAnonymous.java
  backend/src/main/java/com/jujeol/drink/domain/RecommendForMember.java
  backend/src/main/java/com/jujeol/drink/infrastructure/recommend/RecommendationSystem.java
  backend/src/test/java/com/jujeol/drink/acceptance/DrinkAcceptanceTest.java
Labels: 🔥 백엔드

#306 feat: 소나큐브 적용
  .github/workflows/backend-build-test.yml
  .github/workflows/backend-dev-analysis.yml
  backend/build.gradle
Labels: ⚙️ 설정⚒, 🔥 백엔드, 🏗인프라

#278 feat: 마이페이지 선호도 남긴 상품, 리뷰 없을 시 화면 처리 및 헤더 통일
  frontend/src/GlobalStyle.tsx
  frontend/src/components/@shared/Card/Card.ts
  frontend/src/components/@shared/Card/Card.tsx
  frontend/src/components/@shared/Header/Header.styles.ts
  frontend/src/components/@shared/Header/Header.tsx
  frontend/src/components/@shared/SearchBar/SearchBar.styles.ts
  frontend/src/components/Card/PersonalReviewCard.tsx
  frontend/src/components/Header/NavigationHeader.styles.ts
  frontend/src/components/Header/NavigationHeader.tsx
  frontend/src/components/Item/CardItem.tsx
  frontend/src/components/Preview/Preview.styles.ts
  frontend/src/components/Preview/Preview.tsx
  frontend/src/components/RangeWithIcons/RangeWithIcons.styles.ts
  frontend/src/components/RangeWithIcons/RangeWithIcons.tsx
  frontend/src/constants/index.ts
  frontend/src/constants/value.ts
  frontend/src/contexts/UserContext.tsx
  frontend/src/hooks/useDrinks.ts
  frontend/src/mocks/drinks.ts
  frontend/src/mocks/drinksDetail.ts
  frontend/src/mocks/drinksReviews.ts
  frontend/src/mocks/member.ts
  frontend/src/mocks/personalDrinks.ts
  frontend/src/mocks/personalReview.ts
  frontend/src/pages/DrinksDetailPage/NotAuthorized.test.tsx
  frontend/src/pages/DrinksDetailPage/test.tsx
  frontend/src/pages/HomePage/test.tsx
  frontend/src/pages/LoginPage/test.tsx
  frontend/src/pages/MyDrinksPage/MyDrinkItem.tsx
  frontend/src/pages/MyDrinksPage/index.tsx
  frontend/src/pages/MyDrinksPage/test.tsx
  frontend/src/pages/MyPage/NoPreference.styles.ts
  frontend/src/pages/MyPage/NoPreference.tsx
  frontend/src/pages/MyPage/NoReview.styles.tsx
  frontend/src/pages/MyPage/NoReview.tsx
  frontend/src/pages/MyPage/Status.tsx
  frontend/src/pages/MyPage/index.tsx
  frontend/src/pages/MyPage/test.tsx
  frontend/src/pages/MyReviewsPage/index.tsx
  frontend/src/pages/MyReviewsPage/test.tsx
  frontend/src/pages/OauthPage/test.tsx
  frontend/src/pages/ViewAllPage/ViewAllPage.styles.ts
  frontend/src/pages/ViewAllPage/index.tsx
  frontend/src/tests/customRenderer.tsx
  frontend/src/tests/mockTestFunction.ts
  frontend/src/utils/createNickname.ts
Labels: 🕹 기능, 👩‍💻 프론트, 📱 UI

#292 refactor: DB에 이미지 파일 경로 뿐만 아니라 실제 url을 저장하도록 로직 수정
  backend/src/main/java/com/jujeol/DataLoader.java
  backend/src/main/java/com/jujeol/drink/application/DrinkService.java
  backend/src/main/java/com/jujeol/drink/application/dto/DrinkDto.java
  backend/src/main/java/com/jujeol/member/application/MemberService.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application-prod.yml
Labels: 🔥 백엔드, 🛠 리팩토링

#290 feat: 리뷰가 0개일 때의 화면 처리, 리뷰 제한 기능, 리뷰 API 변경에 따른 코드 리팩토링
  frontend/src/apis/requests.ts
  frontend/src/components/@shared/Arrow/Arrow.ts
  frontend/src/components/Review/DisableWriteReview.styles.ts
  frontend/src/components/Review/DisableWriteReview.tsx
  frontend/src/components/Review/NoReviews.styles.ts
  frontend/src/components/Review/NoReviews.tsx
  frontend/src/components/Review/Review.styles.ts
  frontend/src/components/Review/Review.tsx
  frontend/src/components/Review/ReviewCreateForm.tsx
  frontend/src/components/Review/ReviewEditForm.tsx
  frontend/src/constants/requestUrl.ts
  frontend/src/hooks/useReviews.ts
  frontend/src/pages/DrinksDetailPage/index.tsx
  frontend/src/pages/DrinksDetailPage/styles.ts
  frontend/src/types.d.ts
Labels: 🕹 기능, 👩‍💻 프론트, 📱 UI

#311 config: prod 환경 및 에러 로깅 변경
  backend/src/main/java/com/jujeol/commons/aop/LogAop.java
  backend/src/main/resources/application-prod.yml
  backend/src/test/resources/application-test.yml
Labels: ⚙️ 설정⚒, 🔥 백엔드

#315 feat: 스켈레톤 UI 및 로그인시 로딩화면 추가
  frontend/package-lock.json
  frontend/src/components/@shared/FlexBox/FlexBox.ts
  frontend/src/components/@shared/Skeleton/Skeleton.tsx
  frontend/src/components/Banner/Banner.tsx
  frontend/src/components/Item/CardItem.tsx
  frontend/src/components/Item/ListItem.tsx
  frontend/src/components/Review/Review.tsx
  frontend/src/components/Skeleton/DrinksDetailDescriptionSkeleton.tsx
  frontend/src/components/Skeleton/ListItemSkeleton.tsx
  frontend/src/components/Skeleton/PersonalDrinkItemSkeleton.tsx
  frontend/src/components/Skeleton/PersonalReviewItemSkeleton.tsx
  frontend/src/components/Skeleton/ReviewItemSkeleton.tsx
  frontend/src/pages/DrinksDetailPage/index.tsx
  frontend/src/pages/HomePage/DrinkListSection.tsx
  frontend/src/pages/MyDrinksPage/index.tsx
  frontend/src/pages/MyPage/index.tsx
  frontend/src/pages/MyReviewsPage/index.tsx
  frontend/src/pages/OauthPage/index.tsx
  frontend/src/pages/OauthPage/styles.ts
  frontend/src/pages/SearchResultPage/index.tsx
  frontend/src/pages/ViewAllPage/index.tsx
Labels: 🕹 기능, 👩‍💻 프론트

#319 fix: 검색 시 검색어와 가장 유사한 주류가 상위에 없는 오류 수정
  backend/src/main/java/com/jujeol/drink/category/domain/CategoryCustomRepository.java
  backend/src/main/java/com/jujeol/drink/category/domain/CategoryRepository.java
  backend/src/main/java/com/jujeol/drink/category/domain/CategoryRepositoryImpl.java
  backend/src/main/java/com/jujeol/drink/drink/application/DrinkService.java
  backend/src/main/java/com/jujeol/drink/drink/domain/repository/DrinkCustomRepository.java
  backend/src/main/java/com/jujeol/drink/drink/domain/repository/DrinkRepositoryImpl.java
  backend/src/main/java/com/jujeol/preference/application/PreferenceService.java
  backend/src/test/java/com/jujeol/drink/acceptance/DrinkAcceptanceTest.java
Labels: 🔥 백엔드, 🐞 버그

#320 fix: 추천에서 3.0 미만으로 선호도 입력된 주류는 제외
  backend/src/main/java/com/jujeol/drink/drink/domain/repository/DrinkRepository.java
  backend/src/main/java/com/jujeol/drink/recommend/domain/RecommendForMember.java
Labels: 🔥 백엔드, 🐞 버그

#317 feat: 라벨을 붙였을 때도 빌드테스트가 동작하도록 수정
  .github/workflows/backend-build-test.yml
  .github/workflows/front-build-test.yml
Labels: ⚙️ 설정⚒, 🔥 백엔드

#325 refactor: 홈페이지의 검색바 autofocus 기능 해제
  frontend/src/components/@shared/SearchBar/SearchBar.tsx
  frontend/src/pages/HomePage/index.tsx
  frontend/src/pages/SearchPage/index.tsx
Labels: 👩‍💻 프론트, 🐞 버그, 🚨 이슈

#322 fix: 상세페이지 페이지 상단 이동 스크롤 조정 및 비로그인 사용자 선호도 입력하러 가기 버튼 기능 제한
  frontend/src/components/Review/DisableWriteReview.tsx
  frontend/src/components/Review/Review.tsx
  frontend/src/hooks/useInputPreference.ts
  frontend/src/pages/DrinksDetailPage/NotAuthorized.test.tsx
  frontend/src/pages/DrinksDetailPage/index.tsx
  frontend/src/pages/DrinksDetailPage/test.tsx
Labels: 👩‍💻 프론트, 🐞 버그

#327 feat: 관리자페이지 api 변동사항 적용
  backend/src/main/java/com/jujeol/admin/ui/AdminController.java
  backend/src/main/java/com/jujeol/drink/drink/application/DrinkService.java
  backend/src/main/resources/static/admin/html/index.html
  backend/src/main/resources/static/admin/js/admin.js
  backend/src/main/resources/static/admin/js/drinks/component/categoryDropdown.js
  backend/src/main/resources/static/admin/js/drinks/component/drinkInsertModalRow.js
  backend/src/main/resources/static/admin/js/drinks/component/drinkTableColumns.js
  backend/src/main/resources/static/admin/js/drinks/component/pageItem.js
  backend/src/main/resources/static/admin/js/drinks/component/pageItemSelected.js
  backend/src/main/resources/static/admin/js/drinks/dto/DrinkRequest.js
  backend/src/main/resources/static/admin/js/drinks/handler/HandlerDrinkUpdate.js
  backend/src/main/resources/static/admin/js/drinks/model/Drink.js
  backend/src/main/resources/static/admin/js/drinks/view/drinkTable.js
  backend/src/main/resources/static/admin/js/utils/methodFetches.js
Labels: 🔥 백엔드, 📱 UI, 🏗인프라

#329 feat: 테스트에 쿼리카운트 추가
  backend/src/test/java/com/jujeol/RequestBuilder.java
Labels: 🔥 백엔드

#330 fix: 검색어에 카테고리명 입력 시 모든 주류를 반환하는 오류 해결
  backend/src/main/java/com/jujeol/drink/drink/domain/repository/DrinkRepositoryImpl.java
  backend/src/test/java/com/jujeol/drink/acceptance/DrinkAcceptanceTest.java
Labels: 🔥 백엔드, 🐞 버그

#332 feat: 마이페이지에 불편사항 신고 및 건의 링크 추가 및 bio line-height 수정
  frontend/src/components/Preview/Preview.styles.ts
  frontend/src/components/Profile/Profile.styles.ts
  frontend/src/pages/MyPage/NoPreference.styles.ts
  frontend/src/pages/MyPage/NoPreference.tsx
  frontend/src/pages/MyPage/NoReview.styles.tsx
  frontend/src/pages/MyPage/NoReview.tsx
  frontend/src/pages/MyPage/index.tsx
  frontend/src/pages/MyPage/styles.ts
Labels: 🕹 기능, 👩‍💻 프론트, 📱 UI

#333 fix: 추천에서 선호도 평균 순이 없는 것을 수정
  backend/src/main/java/com/jujeol/drink/drink/domain/repository/DrinkRepository.java
Labels: 🔥 백엔드, 🐞 버그

#334 docs: 1.1.0-beta 버전 업 관련 문서 수정
  README.md
  backend/README.md
  backend/build.gradle
  frontend/package.json
Labels: 📋 문서, 🔥 백엔드, 👩‍💻 프론트

#335 feat: prod 환경에서 console 삭제 및 sentry 적용
  frontend/env/.env.prod
  frontend/package-lock.json
  frontend/package.json
  frontend/src/index.tsx
Labels: ⚙️ 설정⚒, 👩‍💻 프론트

#336 fix: 사파리에서 스타일이 제대로 적용되지 않는 이슈 해결
  frontend/src/GlobalStyle.tsx
  frontend/src/components/@shared/FlexBox/FlexBox.ts
  frontend/src/components/@shared/SearchBar/SearchBar.styles.ts
  frontend/src/components/@shared/Skeleton/Skeleton.tsx
  frontend/src/components/Item/CardItem.tsx
  frontend/src/components/Item/ListItem.styles.ts
  frontend/src/components/Profile/Profile.styles.ts
  frontend/src/components/Skeleton/ListItemSkeleton.tsx
  frontend/src/pages/DrinksDetailPage/styles.ts
  frontend/src/pages/MyPage/NoPreference.styles.ts
  frontend/src/pages/MyPage/NoReview.styles.tsx
  frontend/src/pages/MyPage/NoReview.tsx
  frontend/src/pages/OauthPage/index.tsx
  frontend/src/pages/OauthPage/styles.ts
  frontend/src/pages/SearchResultPage/index.tsx
Labels: 👩‍💻 프론트, 📱 UI
