Repository woowacourse-teams/2021-jujeol-jujeol, pull requests merged in 2021-11, with the labels that each got.

#589 feat: 프론트 cache control을 위한 deploy.yml 수정
  .github/workflows/front-dev-deploy.yml
  .github/workflows/front-prod-deploy.yml
Labels: 🕹 기능, 🌈 프론트

#590 fix: Review의 Drink와 Member FetchType을 LAZY로 변경
  backend/src/main/java/com/jujeol/review/domain/Review.java
Labels: 🔥 백엔드, ⚒ 리팩토링

#592 fix: 상세페이지에 들어갔다, 다른 페이지에 들어가면 이전 이미지가 눈에 보이고, 새로운 데이터가 보여지는 문제해결
  frontend/src/pages/DrinksDetailPage/index.tsx
Labels: 🌈 프론트, 🐞 버그

#599 refactor: DataSource.getConnection 을 aop 형식으로 변경
  backend/src/test/java/com/jujeol/testdatabase/DatabaseConfig.java
  backend/src/test/java/com/jujeol/testdatabase/DatasourceAop.java
  backend/src/test/java/com/jujeol/testdatabase/TestDataSource.java
Labels: 🔥 백엔드, ⚒ 리팩토링

#600 chore: 번들 옵션에서 소스맵 생성 비활성화
  frontend/package-lock.json
  frontend/snowpack.config.mjs
Labels: 🌈 프론트

#604 feat: deploy 문을 새로운 서버환경에 맞게 수정
  .github/workflows/backend-build-test.yml
  .github/workflows/backend-dev-analysis.yml
  .github/workflows/backend-prod-deploy.yml
Labels: ⚙️ 설정, 🔥 백엔드, 🏗 인프라, ⚒ 리팩토링, 🎯 배포

#605 fix: name 오타 수정 및 trigger 방식 변경에 따른 if문 삭제
  .github/workflows/backend-prod-deploy.yml
Labels: 🔥 백엔드, 🏗 인프라, ⚒ 리팩토링, 🎯 배포

#606 fix: 잘못 되어 있는 dir 수정
  .github/workflows/backend-prod-deploy.yml
Labels: 🔥 백엔드, 🏗 인프라, 🎯 배포

#607 fix: 잘못 되어 있는 dir 수정 두 번째
  .github/workflows/backend-prod-deploy.yml
Labels: 🏗 인프라, 🎯 배포

#608 chore: prod API URL 변경
  frontend/env/.env.prod
Labels: ⚙️ 설정, 🌈 프론트

#610 feat: easter egg 삭제
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
Labels: 🌈 프론트

#611 feat: workflow에 scp 기능 추가 및 필요없는 prefix dir 삭제
  .github/workflows/backend-prod-deploy.yml
Labels: 🏗 인프라, 🎯 배포
