Repository woowacourse-teams/2021-jujeol-jujeol, pull requests merged in 2021-10, with the labels that each got.

#391 hotfix: flyway 스키마 오류 정정
  backend/src/main/resources/db/migration/prod/V3__drink_add_imageFilePath.sql
Labels: 🔥 백엔드, 🐞 버그

#394 hotfix: 관리자페이지가 잘못 된 서버를 바라보고 있던 문제 수정
  .github/workflows/admin-prod-deploy.yml
  backend/build.gradle
  frontend/package.json
Labels: 🐞 버그, 🚐 핫픽스, 🖥 어드민

#377 feat: 주류 상세페이지 상세 설명 추가 및 이미지 리사이징 기능 구현
  frontend/src/GlobalStyle.tsx
  frontend/src/components/Card/ReviewCard.styles.ts
  frontend/src/components/Card/ReviewCard.tsx
  frontend/src/hooks/useShowMoreContent.ts
  frontend/src/mocks/drinksDetail.ts
  frontend/src/pages/DrinksDetailPage/index.tsx
  frontend/src/pages/DrinksDetailPage/styles.ts
  frontend/src/pages/DrinksDetailPage/test.tsx
Labels: 🕹 기능, 🌈 프론트, 📱유아이

#400 feat: 퍼포먼스 측정 기능 추가
  backend/src/main/java/com/jujeol/performance/PerformanceLogger.java
  backend/src/main/java/com/jujeol/performance/PerformanceLoggingForm.java
  backend/src/main/java/com/jujeol/performance/ProxyConnectionHandler.java
  backend/src/main/java/com/jujeol/performance/ProxyPreparedStatementHandler.java
  backend/src/main/resources/logback-spring.xml
Labels: 🔥 백엔드

#399 hotfix: 리뷰 수정버튼이 snackbar에 가려 안눌리는 버그 해결
  backend/build.gradle
  frontend/package.json
  frontend/src/GlobalStyle.tsx
  frontend/src/components/@shared/Snackbar/Snackbar.styles.ts
Labels: 🌈 프론트, 🐞 버그, 🚐 핫픽스

#405 fix: 로그백 잘못된 ref 삭제
  backend/src/main/resources/logback-spring.xml
Labels: 🔥 백엔드, 🐞 버그

#407 refactor: 퍼포먼스 측정에 api 형식과 method 형식 추가
  backend/src/main/java/com/jujeol/performance/PerformanceLogger.java
  backend/src/main/java/com/jujeol/performance/PerformanceLoggingForm.java
  backend/src/main/java/com/jujeol/performance/RequestApi.java
  backend/src/main/java/com/jujeol/performance/RequestApiExtractor.java
  backend/src/main/java/com/jujeol/performance/annotationDataExtractor/AnnotationDataExtractor.java
  backend/src/main/java/com/jujeol/performance/annotationDataExtractor/DeleteMappingDataExtractor.java
  backend/src/main/java/com/jujeol/performance/annotationDataExtractor/GetMappingDataExtractor.java
  backend/src/main/java/com/jujeol/performance/annotationDataExtractor/PostMappingDataExtractor.java
  backend/src/main/java/com/jujeol/performance/annotationDataExtractor/PutMappingDataExtractor.java
Labels: 🔥 백엔드, ⚒ 리팩토링
