Repository woowacourse-teams/2021-jujeol-jujeol, pull requests merged in 2021-07, with the labels that each got.

#4 chore: 프론트엔드 초기 환경 설정
  .github/ISSUE_TEMPLATE/feature_request.md
  .gitignore
  frontend/.babelrc
  frontend/.eslintrc
  frontend/.gitignore
  frontend/.prettierrc
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/snowpack.config.mjs
  frontend/src/App.tsx
  frontend/src/index.tsx
  frontend/tsconfig.json
Labels: fe, setting

#12 feat: 로그백 및 jpa 설정 파일 추가
  backend/build.gradle
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/banner.txt
  backend/src/main/resources/logback-access.xml
Labels: be, setting

#15 feat: 문서화 기본 설정
  backend/build.gradle
  backend/src/docs/asciidoc/index.adoc
  backend/src/test/java/com/jujeol/AcceptanceTest.java
Labels: be

#20 refactor: RequestBuilder 내부 리팩토링
  backend/src/test/java/com/jujeol/AcceptanceTest.java
  backend/src/test/java/com/jujeol/RequestBuilder.java
Labels: be, enhancement

#16 feat: 홈 화면 마크업 구현
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  backend/build.gradle
  backend/src/main/java/com/jujeol/JujeolApplication.java
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/banner.txt
  backend/src/main/resources/logback-access.xml
  backend/src/test/java/com/jujeol/JujeolApplicationTest.java
  frontend/package-lock.json
  frontend/package.json
  frontend/snowpack.config.mjs
  frontend/src/App.tsx
  frontend/src/GlobalStyle.tsx
  frontend/src/apis/APIProvider.tsx
  frontend/src/components/@shared/SearchBar/SearchBar.styles.ts
  frontend/src/components/@shared/SearchBar/SearchBar.tsx
  frontend/src/components/Card/Card.styles.ts
  frontend/src/components/Card/Card.tsx
  frontend/src/components/Header/Header.styles.ts
  frontend/src/components/Header/Header.tsx
  frontend/src/components/Icons/home.tsx
  frontend/src/components/Icons/human.tsx
  frontend/src/components/Tab/Tab.styles.ts
  frontend/src/components/Tab/Tab.tsx
  frontend/src/constants/color.ts
  frontend/src/constants/index.ts
  frontend/src/constants/path.ts
  frontend/src/constants/zIndex.ts
  frontend/src/index.tsx
  frontend/src/mock/drinks.ts
  frontend/src/pages/HomePage/index.tsx
  frontend/src/pages/HomePage/styles.ts
  frontend/src/styles.ts
  frontend/tsconfig.json
Labels: enhancement, fe

#24 feat: Kakao API 인가코드 받아오는 기능 추가
  backend/src/test/java/com/jujeol/AcceptanceTest.java
  frontend/custom.d.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/snowpack.config.mjs
  frontend/src/App.tsx
  frontend/src/GlobalStyle.tsx
  frontend/src/apis/APIProvider.tsx
  frontend/src/assets/jujeol_logo_square.tsx
  frontend/src/components/@shared/SearchBar/SearchBar.styles.ts
  frontend/src/components/@shared/SearchBar/SearchBar.tsx
  frontend/src/components/Card/Card.styles.ts
  frontend/src/components/Card/Card.tsx
  frontend/src/components/Header/Header.styles.ts
  frontend/src/components/Header/Header.tsx
  frontend/src/components/Header/MainHeader.styles.ts
  frontend/src/components/Header/MainHeader.tsx
  frontend/src/components/Icons/home.tsx
  frontend/src/components/Icons/human.tsx
  frontend/src/components/Icons/symbol_kakao.tsx
  frontend/src/components/SocialLogin/KakaoLogin.styles.ts
  frontend/src/components/SocialLogin/KakaoLogin.tsx
  frontend/src/components/Tab/Tab.styles.ts
  frontend/src/components/Tab/Tab.tsx
  frontend/src/constants/color.ts
  frontend/src/constants/index.ts
  frontend/src/constants/path.ts
  frontend/src/constants/zIndex.ts
  frontend/src/index.tsx
  frontend/src/mock/drinks.ts
  frontend/src/pages/HomePage/index.tsx
  frontend/src/pages/HomePage/styles.ts
  frontend/src/pages/LoginPage/index.tsx
  frontend/src/pages/LoginPage/styles.ts
  frontend/src/pages/OauthPage/index.tsx
  frontend/src/styles.ts
  frontend/tsconfig.json
Labels: enhancement, fe

#22 docs: 백엔드 quick start 문서 추가
  README.md
Labels: be, documentation

#35 feat: RequestBuilder 결과 convert 기능 추가
  backend/src/test/java/com/jujeol/RequestBuilder.java
Labels: be

#38 feat: 로그인 이후 토큰 발급 api 기능 구현
  backend/.gitignore
  backend/build.gradle
  backend/src/docs/asciidoc/index.adoc
  backend/src/main/java/com/jujeol/commons/config/WebAppConfig.java
  backend/src/main/java/com/jujeol/commons/dto/CommonResponseDto.java
  backend/src/main/java/com/jujeol/member/application/LoginService.java
  backend/src/main/java/com/jujeol/member/application/MemberDetails.java
  backend/src/main/java/com/jujeol/member/application/SocialClient.java
  backend/src/main/java/com/jujeol/member/application/SocialLoginStrategyFactory.java
  backend/src/main/java/com/jujeol/member/application/dto/TokenRequest.java
  backend/src/main/java/com/jujeol/member/application/dto/TokenResponse.java
  backend/src/main/java/com/jujeol/member/domain/BirthYear.java
  backend/src/main/java/com/jujeol/member/domain/Member.java
  backend/src/main/java/com/jujeol/member/domain/MemberRepository.java
  backend/src/main/java/com/jujeol/member/domain/Provider.java
  backend/src/main/java/com/jujeol/member/domain/ProviderName.java
  backend/src/main/java/com/jujeol/member/infrastructure/ClientResponseConverter.java
  backend/src/main/java/com/jujeol/member/infrastructure/SocialClientFactory.java
  backend/src/main/java/com/jujeol/member/infrastructure/kakao/KakaoClient.java
  backend/src/main/java/com/jujeol/member/infrastructure/kakao/KakaoMemberDetails.java
  backend/src/main/java/com/jujeol/member/infrastructure/kakao/dto/KakaoAccessTokenRequest.java
  backend/src/main/java/com/jujeol/member/infrastructure/kakao/dto/KakaoAccessTokenResponse.java
  backend/src/main/java/com/jujeol/member/ui/LoginController.java
  backend/src/main/java/com/jujeol/member/util/AuthorizationExtractor.java
  backend/src/main/java/com/jujeol/member/util/JwtTokenProvider.java
  backend/src/main/resources/application.properties
  backend/src/test/java/com/jujeol/AcceptanceTest.java
  backend/src/test/java/com/jujeol/RequestBuilder.java
  backend/src/test/java/com/jujeol/member/TestSocialLoginFactory.java
  backend/src/test/java/com/jujeol/member/acceptance/LoginAcceptanceTest.java
Labels: be

#39 fix: 테스트 깨짐 및 문서 파일 깨짐 현상 해결
  backend/build.gradle
  backend/src/docs/asciidoc/index.adoc
  backend/src/main/java/com/jujeol/commons/config/WebMvcConfig.java
  backend/src/test/java/com/jujeol/JujeolApplicationTest.java
Labels: be

#41 feat: 환경변수 설정 및 전체보기 테스트 코드 작성
  backend/src/docs/asciidoc/index.adoc
  backend/src/main/java/com/jujeol/DataLoader.java
  backend/src/main/java/com/jujeol/JujeolApplication.java
  backend/src/main/java/com/jujeol/commons/config/CorsConfig.java
  backend/src/main/java/com/jujeol/commons/config/WebMvcConfig.java
  backend/src/main/java/com/jujeol/commons/exception/ExceptionCodeAndDetails.java
  backend/src/main/java/com/jujeol/commons/exception/ExceptionController.java
  backend/src/main/java/com/jujeol/commons/exception/JujeolException.java
  backend/src/main/java/com/jujeol/commons/exception/JujeolExceptionDto.java
  backend/src/main/java/com/jujeol/commons/exception/NotFoundErrorCodeException.java
  backend/src/main/java/com/jujeol/drink/application/DrinkService.java
  backend/src/main/java/com/jujeol/drink/application/dto/DrinkResponse.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application.properties
  backend/src/test/java/com/jujeol/RequestBuilder.java
  backend/src/test/java/com/jujeol/commons/exception/CommonsExceptionTest.java
  backend/src/test/java/com/jujeol/commons/exception/acceptance/ExceptionAcceptanceTest.java
  backend/src/test/java/com/jujeol/drink/acceptance/DrinkAcceptanceTest.java
  frontend/.gitignore
  frontend/README.md
  frontend/config.d.ts
  frontend/env/.env.development
  frontend/env/.env.local
  frontend/jest.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.png
  frontend/public/index.html
  frontend/public/jujeol_og_image.png
  frontend/snowpack.config.mjs
  frontend/src/apis/requests.ts
  frontend/src/index.tsx
  frontend/src/mock/drinks.ts
  frontend/src/pages/HomePage/test.tsx
  frontend/tsconfig.json
Labels: fe, setting, test

#42 feat: 전체보기 기능 구현
  frontend/.gitignore
  frontend/README.md
  frontend/config.d.ts
  frontend/env/.env.development
  frontend/env/.env.local
  frontend/jest.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/snowpack.config.mjs
  frontend/src/App.tsx
  frontend/src/GlobalStyle.tsx
  frontend/src/apis/APIProvider.tsx
  frontend/src/apis/requests.ts
  frontend/src/components/@shared/SearchBar/SearchBar.styles.ts
  frontend/src/components/@shared/SearchBar/SearchBar.tsx
  frontend/src/components/Card/Card.styles.ts
  frontend/src/components/Card/Card.tsx
  frontend/src/components/Header/Header.styles.ts
  frontend/src/components/Header/Header.tsx
  frontend/src/components/Icons/home.tsx
  frontend/src/components/Icons/human.tsx
  frontend/src/components/Tab/Tab.styles.ts
  frontend/src/components/Tab/Tab.tsx
  frontend/src/constants/color.ts
  frontend/src/constants/index.ts
  frontend/src/constants/path.ts
  frontend/src/constants/zIndex.ts
  frontend/src/index.tsx
  frontend/src/mock/drinks.ts
  frontend/src/pages/HomePage/index.tsx
  frontend/src/pages/HomePage/styles.ts
  frontend/src/pages/HomePage/test.tsx
  frontend/src/styles.ts
  frontend/tsconfig.json
Labels: be, enhancement, fe, setting, test

#46 feat: backlog 운영 환경에 따라 콘솔 및 파일로 변경
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application-prod.yml
  backend/src/main/resources/application.properties
  backend/src/main/resources/application.yml
  backend/src/main/resources/logback-access.xml
  backend/src/main/resources/logback-spring.xml
Labels: be, enhancement

#52 chore: netlify 리다이렉트를 위해 netlify.toml 설정 추가
  frontend/public/netlify.toml
  frontend/src/App.tsx
Labels: fe, setting

#47 feat: S3 이미지로 변경 및 backend quick start 문서 작성
  README.md
  backend/README.md
  backend/src/main/java/com/jujeol/DataLoader.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application.properties
Labels: be, documentation, enhancement

#53 feat: 로그인 테스트 코드 작성
  frontend/src/pages/LoginPage/test.tsx
  frontend/src/pages/OauthPage/index.tsx
  frontend/src/pages/OauthPage/test.tsx
Labels: fe, test

#69 feat: 내 정보 조회 기능 구현
  backend/build.gradle
  backend/src/docs/asciidoc/index.adoc
  backend/src/main/java/com/jujeol/DataLoader.java
  backend/src/main/java/com/jujeol/commons/exception/ExceptionCodeAndDetails.java
  backend/src/main/java/com/jujeol/drink/application/DrinkService.java
  backend/src/main/java/com/jujeol/drink/application/dto/DrinkDetailResponse.java
  backend/src/main/java/com/jujeol/drink/application/dto/DrinkSimpleResponse.java
  backend/src/main/java/com/jujeol/drink/application/dto/ReviewRequest.java
  backend/src/main/java/com/jujeol/drink/domain/Category.java
  backend/src/main/java/com/jujeol/drink/domain/Drink.java
  backend/src/main/java/com/jujeol/drink/domain/DrinkEnglishName.java
  backend/src/main/java/com/jujeol/drink/domain/Review.java
  backend/src/main/java/com/jujeol/drink/domain/ReviewRepository.java
  backend/src/main/java/com/jujeol/drink/exception/InvalidEnglishNameException.java
  backend/src/main/java/com/jujeol/drink/exception/NotFoundDrinkException.java
  backend/src/main/java/com/jujeol/drink/exception/NotFoundReviewException.java
  backend/src/main/java/com/jujeol/drink/ui/DrinkController.java
  backend/src/main/java/com/jujeol/member/application/MemberService.java
  backend/src/main/java/com/jujeol/member/application/dto/MemberResponse.java
  backend/src/main/java/com/jujeol/member/application/dto/PreferenceRequest.java
  backend/src/main/java/com/jujeol/member/config/AuthenticationPrincipalConfig.java
  backend/src/main/java/com/jujeol/member/domain/AuthenticationPrincipal.java
  backend/src/main/java/com/jujeol/member/domain/LoginMember.java
  backend/src/main/java/com/jujeol/member/domain/Preference.java
  backend/src/main/java/com/jujeol/member/domain/PreferenceRepository.java
  backend/src/main/java/com/jujeol/member/exception/InvalidTokenException.java
  backend/src/main/java/com/jujeol/member/exception/NoSuchMemberException.java
  backend/src/main/java/com/jujeol/member/ui/MemberController.java
  backend/src/main/java/com/jujeol/member/util/AuthenticationPrincipalArgumentResolver.java
  backend/src/test/java/com/jujeol/AcceptanceTest.java
  backend/src/test/java/com/jujeol/JujeolApplicationTest.java
  backend/src/test/java/com/jujeol/RequestBuilder.java
  backend/src/test/java/com/jujeol/TestDataLoader.java
  backend/src/test/java/com/jujeol/drink/acceptance/DrinkAcceptanceTest.java
  backend/src/test/java/com/jujeol/drink/domain/DrinkEnglishNameTest.java
  backend/src/test/java/com/jujeol/drink/domain/ReviewRepositoryTest.java
  backend/src/test/java/com/jujeol/member/acceptance/MemberAcceptanceTest.java
  backend/src/test/java/com/jujeol/member/domain/MemberRepositoryTest.java
Labels: 🔥 백엔드, 🕹 기능

#76 fix: 주류 상세보기 api 수정
  backend/src/main/java/com/jujeol/drink/domain/DrinkEnglishName.java
  backend/src/main/java/com/jujeol/drink/ui/dto/CategoryResponse.java
  backend/src/main/java/com/jujeol/drink/ui/dto/DrinkDetailResponse.java
  backend/src/main/resources/static/index.html
  backend/src/test/java/com/jujeol/drink/domain/DrinkEnglishNameTest.java
Labels: 🐞 버그, 📋 문서, 🔥 백엔드

#87 refactor: 해당 주류에 선호도가 없을 때 예외 대신 0 반환
  backend/src/main/java/com/jujeol/commons/exception/ExceptionCodeAndDetails.java
  backend/src/main/java/com/jujeol/drink/application/DrinkService.java
  backend/src/main/java/com/jujeol/drink/ui/DrinkController.java
  backend/src/main/java/com/jujeol/member/application/MemberService.java
  backend/src/main/java/com/jujeol/member/application/dto/PreferenceRequest.java
  backend/src/main/java/com/jujeol/member/domain/Preference.java
  backend/src/main/java/com/jujeol/member/exception/NoSuchPreferenceException.java
  backend/src/test/java/com/jujeol/TestDataLoader.java
  backend/src/test/java/com/jujeol/drink/acceptance/DrinkAcceptanceTest.java
  backend/src/test/java/com/jujeol/member/domain/PreferenceRepositoryTest.java
Labels: 🐞 버그, 🔥 백엔드

#90 feat: 리뷰 정보에 날짜 추가 및 리뷰 작성 제한 기능 추가
  backend/.gitignore
  backend/src/docs/asciidoc/index.adoc
  backend/src/main/java/com/jujeol/DataLoader.java
  backend/src/main/java/com/jujeol/commons/exception/ExceptionCodeAndDetails.java
  backend/src/main/java/com/jujeol/drink/application/ReviewService.java
  backend/src/main/java/com/jujeol/drink/application/dto/ReviewResponse.java
  backend/src/main/java/com/jujeol/drink/domain/Drink.java
  backend/src/main/java/com/jujeol/drink/domain/DrinkEnglishName.java
  backend/src/main/java/com/jujeol/drink/domain/Review.java
  backend/src/main/java/com/jujeol/drink/domain/ReviewRepository.java
  backend/src/main/java/com/jujeol/drink/exception/CreateReviewLimitException.java
  backend/src/main/java/com/jujeol/drink/ui/DrinkController.java
  backend/src/main/java/com/jujeol/drink/ui/dto/DrinkDetailResponse.java
  backend/src/main/java/com/jujeol/member/config/AuthenticationPrincipalConfig.java
  backend/src/main/java/com/jujeol/member/ui/LoginInterceptor.java
  backend/src/test/java/com/jujeol/AcceptanceTest.java
  backend/src/test/java/com/jujeol/RequestBuilder.java
  backend/src/test/java/com/jujeol/TestDataLoader.java
  backend/src/test/java/com/jujeol/drink/acceptance/ReviewAcceptanceTest.java
  backend/src/test/java/com/jujeol/drink/domain/ReviewRepositoryTest.java
  backend/src/test/java/com/jujeol/member/acceptance/MemberAcceptanceTest.java
  backend/src/test/java/com/jujeol/member/domain/PreferenceRepositoryTest.java
Labels: 🔥 백엔드, 🕹 기능

#97 fix: 리뷰 생성 및 수정시 리뷰 내용 제한 예외 추가
  backend/src/docs/asciidoc/index.adoc
  backend/src/main/java/com/jujeol/commons/exception/ExceptionCodeAndDetails.java
  backend/src/main/java/com/jujeol/drink/domain/Review.java
  backend/src/main/java/com/jujeol/drink/domain/ReviewContent.java
  backend/src/main/java/com/jujeol/drink/exception/InvalidReviewContentException.java
  backend/src/test/java/com/jujeol/drink/acceptance/ReviewAcceptanceTest.java
  backend/src/test/java/com/jujeol/drink/domain/ReviewContentTest.java
Labels: 🐞 버그, 📋 문서, 🔥 백엔드

#98 [FE] 상세보기, 선호도, 리뷰 기능 구현
  frontend/config.d.ts
  frontend/custom.d.ts
  frontend/package-lock.json
  frontend/public/assets/default.png
  frontend/public/index.html
  frontend/snowpack.config.mjs
  frontend/src/App.tsx
  frontend/src/apis/requests.ts
  frontend/src/assets/default.png
  frontend/src/components/Card/Card.styles.ts
  frontend/src/components/Card/Card.tsx
  frontend/src/components/Card/ReviewCard.styles.ts
  frontend/src/components/Card/ReviewCard.tsx
  frontend/src/components/Header/MainHeader.styles.ts
  frontend/src/components/Header/MainHeader.tsx
  frontend/src/components/Icons/star.tsx
  frontend/src/components/Modal/Modal.styles.ts
  frontend/src/components/Modal/Modal.tsx
  frontend/src/components/Modal/ModalProvider.tsx
  frontend/src/components/Property/Property.styles.ts
  frontend/src/components/Property/Property.tsx
  frontend/src/components/RangeWithIcons/RangeWithIcons.styles.ts
  frontend/src/components/RangeWithIcons/RangeWithIcons.tsx
  frontend/src/components/Review/Review.styles.ts
  frontend/src/components/Review/Review.tsx
  frontend/src/components/Review/ReviewCreateForm.styles.ts
  frontend/src/components/Review/ReviewCreateForm.tsx
  frontend/src/components/Review/ReviewEditForm.styles.ts
  frontend/src/components/Review/ReviewEditForm.tsx
  frontend/src/components/Tab/Tab.tsx
  frontend/src/constants/color.ts
  frontend/src/constants/index.ts
  frontend/src/constants/localStorage.ts
  frontend/src/constants/messages.ts
  frontend/src/constants/path.ts
  frontend/src/constants/portal.ts
  frontend/src/constants/preference.ts
  frontend/src/constants/requestUrl.ts
  frontend/src/constants/review.ts
  frontend/src/constants/zIndex.ts
  frontend/src/contexts/UserContext.tsx
  frontend/src/index.tsx
  frontend/src/mocks/drinks.ts
  frontend/src/mocks/drinksDetail.ts
  frontend/src/mocks/drinksReviews.ts
  frontend/src/pages/DrinksDetailPage/index.tsx
  frontend/src/pages/DrinksDetailPage/propertyData.ts
  frontend/src/pages/DrinksDetailPage/styles.ts
  frontend/src/pages/HomePage/index.tsx
  frontend/src/pages/HomePage/test.tsx
  frontend/src/pages/LoginPage/index.tsx
  frontend/src/pages/OauthPage/index.tsx
  frontend/src/portals/Portal.ts
  frontend/src/styles.ts
  frontend/src/types.d.ts
  frontend/src/utils/createNickname.ts
  frontend/src/utils/error.ts
  frontend/src/utils/localStorage.ts
Labels: 👩‍💻 프론트, 🕹 기능

#100 feat: 관리자 페이지 프론트엔드 기능 구현
  README.md
  backend/src/main/java/com/jujeol/admin/PageResponseAssembler.java
  backend/src/main/java/com/jujeol/admin/ui/DrinkService.java
  backend/src/main/java/com/jujeol/admin/ui/DummyData.java
  backend/src/main/java/com/jujeol/admin/ui/dto/CategoryRequest.java
  backend/src/main/java/com/jujeol/admin/ui/dto/CategoryResponse.java
  backend/src/main/java/com/jujeol/admin/ui/dto/DrinkRequest.java
  backend/src/main/java/com/jujeol/commons/config/WebMvcConfig.java
  backend/src/main/resources/static/admin/bootstrap/bootstrap.bundle.min.js
  backend/src/main/resources/static/admin/bootstrap/bootstrap.bundle.min.js.map
  backend/src/main/resources/static/admin/bootstrap/bootstrap.min.css
  backend/src/main/resources/static/admin/bootstrap/bootstrap.min.css.map
  backend/src/main/resources/static/admin/css/dashboard.css
  backend/src/main/resources/static/admin/html/index.html
  backend/src/main/resources/static/admin/js/admin.js
  backend/src/main/resources/static/admin/js/drinks/component/drinkTableColumns.js
  backend/src/main/resources/static/admin/js/drinks/component/drinkTableRow.js
  backend/src/main/resources/static/admin/js/drinks/component/drinkUpdateButton.js
  backend/src/main/resources/static/admin/js/drinks/dto/DrinkRequest.js
  backend/src/main/resources/static/admin/js/drinks/handler/HandlerDrinkBatchInsert.js
  backend/src/main/resources/static/admin/js/drinks/handler/HandlerDrinkDelete.js
  backend/src/main/resources/static/admin/js/drinks/handler/HandlerDrinkUpdate.js
  backend/src/main/resources/static/admin/js/drinks/model/Drink.js
  backend/src/main/resources/static/admin/js/drinks/model/Drinks.js
  backend/src/main/resources/static/admin/js/drinks/view/drinkTable.js
  backend/src/main/resources/static/admin/js/utils/methodFetches.js
  backend/src/main/resources/static/admin/js/utils/querySelector.js
  backend/src/main/resources/static/admin/js/utils/validator.js
Labels: 👩‍💻 프론트, 📱 UI, 🕹 기능

#102 feat: 리뷰 300자 글자 제한 추가
  backend/src/main/java/com/jujeol/drink/domain/Review.java
  backend/src/main/java/com/jujeol/drink/domain/ReviewContent.java
  backend/src/test/java/com/jujeol/drink/acceptance/ReviewAcceptanceTest.java
Labels: 🐞 버그, 🔥 백엔드

#104 fix: 리뷰 글자수 300자 변경
  backend/src/main/java/com/jujeol/drink/domain/Review.java
  backend/src/main/java/com/jujeol/drink/domain/ReviewContent.java
  backend/src/test/java/com/jujeol/drink/acceptance/ReviewAcceptanceTest.java
Labels: 🐞 버그, 🔥 백엔드

#107 fix: 모바일 사파리에서 선호도 슬라이드 제대로 되지 않는 이슈 해결
  frontend/src/GlobalStyle.tsx
  frontend/src/components/RangeWithIcons/RangeWithIcons.styles.ts
Labels: 🐞 버그, 👩‍💻 프론트, 📱 UI, 🚨 이슈

#135 fix: PageInfo 에 currentPage 가 1이 더 증가되는 현상 수정
  backend/src/main/java/com/jujeol/commons/dto/PageInfo.java
  backend/src/test/java/com/jujeol/AcceptanceTest.java
  backend/src/test/java/com/jujeol/RequestBuilder.java
  backend/src/test/java/com/jujeol/admin/acceptance/AdminAcceptanceTest.java
  backend/src/test/java/com/jujeol/drink/acceptance/DrinkAcceptanceTest.java
  backend/src/test/java/com/jujeol/drink/acceptance/ReviewAcceptanceTest.java
Labels: 🐞 버그, 🔥 백엔드

#133 feat: PathMatcherInterceptor 기능 구현
  backend/src/main/java/com/jujeol/commons/interceptor/PathContainer.java
  backend/src/main/java/com/jujeol/commons/interceptor/PathMatcherInterceptor.java
  backend/src/main/java/com/jujeol/commons/interceptor/PathMethod.java
  backend/src/main/java/com/jujeol/commons/interceptor/RequestPath.java
  backend/src/main/java/com/jujeol/member/config/AuthenticationPrincipalConfig.java
  backend/src/main/java/com/jujeol/member/ui/interceptor/LoginInterceptor.java
Labels: 🔥 백엔드

#136 feat: 마이페이지에서 내가 마신 술, 내가 남긴 리뷰 모아보기 dummy API
  backend/src/docs/asciidoc/index.adoc
  backend/src/main/java/com/jujeol/drink/application/dto/ReviewDto.java
  backend/src/main/java/com/jujeol/member/application/MemberService.java
  backend/src/main/java/com/jujeol/member/ui/MemberController.java
  backend/src/main/java/com/jujeol/member/ui/dto/MemberDrinkResponse.java
  backend/src/main/java/com/jujeol/member/ui/dto/MemberReviewResponse.java
  backend/src/main/java/com/jujeol/member/ui/dto/ReviewDrinkResponse.java
  backend/src/test/java/com/jujeol/member/acceptance/MemberInfoAcceptanceTest.java
Labels: 📋 문서, 🔥 백엔드, 🕹 기능

#137 feat: 마이페이지 화면 마크업 구현
  frontend/src/App.tsx
  frontend/src/GlobalStyle.tsx
  frontend/src/components/@shared/Card/Card.styles.ts
  frontend/src/components/@shared/Card/Card.tsx
  frontend/src/components/@shared/Image/Image.ts
  frontend/src/components/Card/PersonalReviewCard.tsx
  frontend/src/components/Modal/Modal.styles.ts
  frontend/src/components/Preview/Preview.styles.ts
  frontend/src/components/Preview/Preview.tsx
  frontend/src/components/Profile/Profile.styles.ts
  frontend/src/components/Profile/Profile.tsx
  frontend/src/components/Review/TextReview.styles.ts
  frontend/src/components/Review/TextReview.tsx
  frontend/src/components/ScrollList/Horizontal.styles.ts
  frontend/src/components/ScrollList/Horizontal.tsx
  frontend/src/components/Tab/Tab.styles.ts
  frontend/src/pages/HomePage/index.tsx
  frontend/src/pages/MyPage/index.tsx
  frontend/src/pages/MyPage/styles.ts
  frontend/src/styles.ts
  frontend/src/styles/Flex.ts
Labels: 👩‍💻 프론트, 📱 UI

#131 feat: 주류 단일 조회시 카테고리와 평균 더미 데이터 추가
  backend/src/main/java/com/jujeol/DataLoader.java
  backend/src/main/java/com/jujeol/drink/application/dto/DrinkDto.java
  backend/src/main/java/com/jujeol/drink/application/dto/DrinkRequestDto.java
  backend/src/main/java/com/jujeol/drink/domain/Drink.java
  backend/src/main/java/com/jujeol/drink/ui/dto/DrinkDetailResponse.java
  backend/src/test/java/com/jujeol/TestDataLoader.java
  backend/src/test/java/com/jujeol/drink/domain/ReviewRepositoryTest.java
  backend/src/test/java/com/jujeol/member/domain/PreferenceRepositoryTest.java
Labels: 🔥 백엔드

#142 feat: 카테고리 정책 변경 및 카테고리 테이블 구현
  backend/src/main/java/com/jujeol/DataLoader.java
  backend/src/main/java/com/jujeol/admin/ui/dto/AdminDrinkRequest.java
  backend/src/main/java/com/jujeol/admin/ui/dto/AdminDrinkResponse.java
  backend/src/main/java/com/jujeol/admin/ui/dto/CategoryRequest.java
  backend/src/main/java/com/jujeol/admin/ui/dto/CategoryRequestDto.java
  backend/src/main/java/com/jujeol/admin/ui/dto/CategoryResponse.java
  backend/src/main/java/com/jujeol/admin/ui/dto/DrinkRequest.java
  backend/src/main/java/com/jujeol/drink/application/DrinkService.java
  backend/src/main/java/com/jujeol/drink/application/dto/DrinkDto.java
  backend/src/main/java/com/jujeol/drink/application/dto/DrinkRequestDto.java
  backend/src/main/java/com/jujeol/drink/domain/Category.java
  backend/src/main/java/com/jujeol/drink/domain/Drink.java
  backend/src/main/java/com/jujeol/drink/domain/repository/CategoryRepository.java
  backend/src/main/java/com/jujeol/drink/domain/repository/DrinkRepositoryImpl.java
  backend/src/main/java/com/jujeol/drink/ui/dto/DrinkDetailResponse.java
  backend/src/main/resources/static/admin/js/drinks/handler/HandlerDrinkBatchInsert.js
  backend/src/main/resources/static/admin/js/drinks/handler/HandlerDrinkUpdate.js
  backend/src/test/java/com/jujeol/TestDataLoader.java
  backend/src/test/java/com/jujeol/admin/AdminDrinkRequestContainer.java
  backend/src/test/java/com/jujeol/admin/acceptance/AdminAcceptanceTest.java
  backend/src/test/java/com/jujeol/drink/domain/ReviewContentTest.java
  backend/src/test/java/com/jujeol/drink/domain/repository/ReviewRepositoryTest.java
  backend/src/test/java/com/jujeol/member/domain/PreferenceRepositoryTest.java
Labels: 🔥 백엔드, 🕹 기능

#143 feat: 홈화면 및 전체보기 페이지 API 연동
  frontend/src/GlobalStyle.tsx
  frontend/src/components/Section/Section.tsx
  frontend/src/pages/HomePage/DrinkListSection.tsx
  frontend/src/pages/ViewAllPage/ViewAllPage.styles.ts
  frontend/src/pages/ViewAllPage/ViewAllPage.tsx
Labels: 👩‍💻 프론트, 🕹 기능

#144 feat: 마이페이지에서 내가 마신 술, 내가 남긴 리뷰 모아보기
  backend/src/main/java/com/jujeol/DataLoader.java
  backend/src/main/java/com/jujeol/commons/domain/BaseEntity.java
  backend/src/main/java/com/jujeol/drink/application/DrinkService.java
  backend/src/main/java/com/jujeol/drink/application/ReviewService.java
  backend/src/main/java/com/jujeol/drink/application/dto/DrinkDto.java
  backend/src/main/java/com/jujeol/drink/application/dto/ReviewDto.java
  backend/src/main/java/com/jujeol/drink/domain/Review.java
  backend/src/main/java/com/jujeol/drink/domain/repository/ReviewRepository.java
  backend/src/main/java/com/jujeol/member/application/MemberService.java
  backend/src/main/java/com/jujeol/member/domain/MemberRepository.java
  backend/src/main/java/com/jujeol/member/domain/Preference.java
  backend/src/main/java/com/jujeol/member/domain/PreferenceRepository.java
  backend/src/main/java/com/jujeol/member/ui/MemberController.java
  backend/src/main/java/com/jujeol/member/ui/dto/MemberReviewResponse.java
  backend/src/main/java/com/jujeol/member/ui/dto/ReviewDrinkResponse.java
  backend/src/test/java/com/jujeol/TestDataLoader.java
  backend/src/test/java/com/jujeol/drink/acceptance/DrinkAcceptanceTest.java
  backend/src/test/java/com/jujeol/drink/domain/repository/ReviewRepositoryTest.java
  backend/src/test/java/com/jujeol/member/acceptance/MemberInfoAcceptanceTest.java
  backend/src/test/java/com/jujeol/member/domain/MemberInfoRepositoryTest.java
  backend/src/test/java/com/jujeol/member/domain/PreferenceRepositoryTest.java
Labels: 🔥 백엔드, 🕹 기능

#140 feat: 랜덤 닉네임 생성 및 멤버 닉네임/자기소개 수정 기능
  backend/src/docs/asciidoc/index.adoc
  backend/src/main/java/com/jujeol/DataLoader.java
  backend/src/main/java/com/jujeol/commons/exception/ExceptionCodeAndDetails.java
  backend/src/main/java/com/jujeol/drink/application/DrinkService.java
  backend/src/main/java/com/jujeol/drink/domain/Category.java
  backend/src/main/java/com/jujeol/member/application/AddHashNicknameCreator.java
  backend/src/main/java/com/jujeol/member/application/CsvCheersExpressionsRepository.java
  backend/src/main/java/com/jujeol/member/application/LoginService.java
  backend/src/main/java/com/jujeol/member/application/MemberService.java
  backend/src/main/java/com/jujeol/member/application/dto/MemberDto.java
  backend/src/main/java/com/jujeol/member/application/dto/PreferenceDto.java
  backend/src/main/java/com/jujeol/member/application/dto/PreferenceRequest.java
  backend/src/main/java/com/jujeol/member/application/dto/SocialProviderCodeDto.java
  backend/src/main/java/com/jujeol/member/application/dto/TokenDto.java
  backend/src/main/java/com/jujeol/member/domain/Biography.java
  backend/src/main/java/com/jujeol/member/domain/Member.java
  backend/src/main/java/com/jujeol/member/domain/MemberRepository.java
  backend/src/main/java/com/jujeol/member/domain/Preference.java
  backend/src/main/java/com/jujeol/member/domain/nickname/CheersExpression.java
  backend/src/main/java/com/jujeol/member/domain/nickname/CheersExpressionsRepository.java
  backend/src/main/java/com/jujeol/member/domain/nickname/InmemoryCheersExpression.java
  backend/src/main/java/com/jujeol/member/domain/nickname/InmemoryCheersExpressionRepository.java
  backend/src/main/java/com/jujeol/member/domain/nickname/Nickname.java
  backend/src/main/java/com/jujeol/member/domain/nickname/NicknameCreator.java
  backend/src/main/java/com/jujeol/member/exception/InvalidUserBiographyLengthException.java
  backend/src/main/java/com/jujeol/member/exception/InvalidUserNicknameCharacterException.java
  backend/src/main/java/com/jujeol/member/exception/InvalidUserNicknameLengthException.java
  backend/src/main/java/com/jujeol/member/ui/LoginController.java
  backend/src/main/java/com/jujeol/member/ui/MemberController.java
  backend/src/main/java/com/jujeol/member/ui/dto/MemberRequest.java
  backend/src/main/java/com/jujeol/member/ui/dto/MemberResponse.java
  backend/src/main/java/com/jujeol/member/ui/dto/PreferenceResponse.java
  backend/src/main/java/com/jujeol/member/ui/dto/SocialProviderCodeRequest.java
  backend/src/main/resources/rowdata/cheersExpression.csv
  backend/src/test/java/com/jujeol/AcceptanceTest.java
  backend/src/test/java/com/jujeol/RequestBuilder.java
  backend/src/test/java/com/jujeol/TestDataLoader.java
  backend/src/test/java/com/jujeol/drink/domain/repository/ReviewRepositoryTest.java
  backend/src/test/java/com/jujeol/member/acceptance/LoginAcceptanceTest.java
  backend/src/test/java/com/jujeol/member/acceptance/MemberAcceptanceTest.java
  backend/src/test/java/com/jujeol/member/domain/BiographyTest.java
  backend/src/test/java/com/jujeol/member/domain/MemberRepositoryTest.java
  backend/src/test/java/com/jujeol/member/domain/NicknameTest.java
  backend/src/test/java/com/jujeol/member/domain/PreferenceRepositoryTest.java
  backend/src/test/java/com/jujeol/member/fixture/SocialLoginMemberFixture.java
  backend/src/test/java/com/jujeol/member/fixture/TestSocialLoginFactory.java
  backend/src/test/java/com/jujeol/member/fixture/TestsCheersExpressionRepository.java
Labels: 🔥 백엔드, 🕹 기능

#149 fix: 멤버 닉네임 및 자기소개 수정 기능 컴파일 오류 수정
  backend/src/main/java/com/jujeol/drink/application/dto/DrinkRequestDto.java
  backend/src/main/java/com/jujeol/drink/domain/Category.java
  backend/src/main/java/com/jujeol/member/application/LoginService.java
  backend/src/main/java/com/jujeol/member/config/AuthenticationPrincipalConfig.java
  backend/src/main/java/com/jujeol/member/ui/dto/MemberRequest.java
  backend/src/test/java/com/jujeol/TestDataLoader.java
  backend/src/test/java/com/jujeol/drink/domain/repository/ReviewRepositoryTest.java
  backend/src/test/java/com/jujeol/member/acceptance/MemberInfoAcceptanceTest.java
  backend/src/test/java/com/jujeol/member/domain/MemberInfoRepositoryTest.java
Labels: 🐞 버그, 🔥 백엔드

#145 feat: 선호도 평균 추가
  backend/src/main/java/com/jujeol/DataLoader.java
  backend/src/main/java/com/jujeol/admin/ui/AdminController.java
  backend/src/main/java/com/jujeol/admin/ui/dto/AdminDrinkRequest.java
  backend/src/main/java/com/jujeol/drink/application/DrinkService.java
  backend/src/main/java/com/jujeol/drink/application/dto/AdminDrinkRequestDto.java
  backend/src/main/java/com/jujeol/drink/domain/Category.java
  backend/src/main/java/com/jujeol/drink/domain/Drink.java
  backend/src/main/java/com/jujeol/member/application/MemberService.java
  backend/src/main/java/com/jujeol/member/domain/Preference.java
  backend/src/main/java/com/jujeol/member/domain/PreferenceRepository.java
  backend/src/test/java/com/jujeol/TestDataLoader.java
  backend/src/test/java/com/jujeol/drink/domain/repository/ReviewRepositoryTest.java
  backend/src/test/java/com/jujeol/member/acceptance/MemberAcceptanceTest.java
  backend/src/test/java/com/jujeol/member/domain/PreferenceRepositoryTest.java
Labels: 🔥 백엔드, 🕹 기능

#151 feat: 컨플릭트 해결
  backend/src/test/java/com/jujeol/member/domain/MemberInfoRepositoryTest.java
  backend/src/test/java/com/jujeol/member/domain/PreferenceRepositoryTest.java
Labels: 🐞 버그, 🔥 백엔드

#146 feat: Drink 조회수 구현 및 선호도, 조회수 기반 주류 추천 기능 구현
  backend/src/docs/asciidoc/index.adoc
  backend/src/main/java/com/jujeol/DataLoader.java
  backend/src/main/java/com/jujeol/admin/ui/AdminController.java
  backend/src/main/java/com/jujeol/admin/ui/dto/AdminDrinkRequest.java
  backend/src/main/java/com/jujeol/commons/exception/ExceptionCodeAndDetails.java
  backend/src/main/java/com/jujeol/drink/application/DrinkService.java
  backend/src/main/java/com/jujeol/drink/application/ReviewService.java
  backend/src/main/java/com/jujeol/drink/application/ViewCountService.java
  backend/src/main/java/com/jujeol/drink/application/dto/AdminDrinkRequestDto.java
  backend/src/main/java/com/jujeol/drink/application/dto/DrinkDto.java
  backend/src/main/java/com/jujeol/drink/application/dto/MemberDto.java
  backend/src/main/java/com/jujeol/drink/application/dto/ReviewResponse.java
  backend/src/main/java/com/jujeol/drink/application/dto/ThemeDto.java
  backend/src/main/java/com/jujeol/drink/domain/Drink.java
  backend/src/main/java/com/jujeol/drink/domain/RecommendationTheme.java
  backend/src/main/java/com/jujeol/drink/domain/ViewCount.java
  backend/src/main/java/com/jujeol/drink/domain/repository/DrinkRepository.java
  backend/src/main/java/com/jujeol/drink/domain/repository/DrinkRepositoryImpl.java
  backend/src/main/java/com/jujeol/drink/domain/repository/ReviewRepository.java
  backend/src/main/java/com/jujeol/drink/domain/repository/ViewCountRepository.java
  backend/src/main/java/com/jujeol/drink/exception/NotFoundViewCountException.java
  backend/src/main/java/com/jujeol/drink/ui/DrinkController.java
  backend/src/main/java/com/jujeol/drink/ui/dto/DrinkDetailResponse.java
  backend/src/main/java/com/jujeol/drink/ui/dto/ThemeRequest.java
  backend/src/main/java/com/jujeol/member/domain/PreferenceRepository.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/jujeol/AcceptanceTest.java
  backend/src/test/java/com/jujeol/TestDataLoader.java
  backend/src/test/java/com/jujeol/admin/AdminDrinkRequestContainer.java
  backend/src/test/java/com/jujeol/drink/acceptance/DrinkAcceptanceTest.java
  backend/src/test/java/com/jujeol/drink/domain/repository/DrinkRepositoryTest.java
  backend/src/test/java/com/jujeol/drink/domain/repository/ReviewRepositoryTest.java
  backend/src/test/java/com/jujeol/member/domain/MemberInfoRepositoryTest.java
  backend/src/test/java/com/jujeol/member/domain/PreferenceRepositoryTest.java
Labels: 🔥 백엔드, 🕹 기능

#158 feat: 검색, 카테고리 조회 dummyAPI 구현 및 Category에 key 추가
  backend/src/docs/asciidoc/index.adoc
  backend/src/main/java/com/jujeol/DataLoader.java
  backend/src/main/java/com/jujeol/admin/ui/AdminController.java
  backend/src/main/java/com/jujeol/admin/ui/dto/AdminCategory.java
  backend/src/main/java/com/jujeol/admin/ui/dto/AdminCategoryResponse.java
  backend/src/main/java/com/jujeol/admin/ui/dto/AdminDrinkRequest.java
  backend/src/main/java/com/jujeol/admin/ui/dto/AdminDrinkResponse.java
  backend/src/main/java/com/jujeol/admin/ui/dto/CategoryRequestDto.java
  backend/src/main/java/com/jujeol/admin/ui/dto/CategoryResponse.java
  backend/src/main/java/com/jujeol/admin/ui/dto/DrinkRequest.java
  backend/src/main/java/com/jujeol/drink/application/CategoryService.java
  backend/src/main/java/com/jujeol/drink/application/DrinkService.java
  backend/src/main/java/com/jujeol/drink/application/dto/CategoryDto.java
  backend/src/main/java/com/jujeol/drink/application/dto/DrinkDto.java
  backend/src/main/java/com/jujeol/drink/application/dto/DrinkRequestDto.java
  backend/src/main/java/com/jujeol/drink/application/dto/SearchDto.java
  backend/src/main/java/com/jujeol/drink/domain/Category.java
  backend/src/main/java/com/jujeol/drink/domain/repository/CategoryRepository.java
  backend/src/main/java/com/jujeol/drink/ui/CategoryController.java
  backend/src/main/java/com/jujeol/drink/ui/DrinkController.java
  backend/src/main/java/com/jujeol/drink/ui/dto/CategoryResponse.java
  backend/src/main/java/com/jujeol/drink/ui/dto/DrinkDetailResponse.java
  backend/src/main/java/com/jujeol/drink/ui/dto/SearchRequest.java
  backend/src/main/java/com/jujeol/member/application/LoginService.java
  backend/src/main/java/com/jujeol/member/domain/Member.java
  backend/src/test/java/com/jujeol/TestDataLoader.java
  backend/src/test/java/com/jujeol/admin/AdminDrinkRequestContainer.java
  backend/src/test/java/com/jujeol/admin/acceptance/AdminAcceptanceTest.java
  backend/src/test/java/com/jujeol/drink/acceptance/CategoryAcceptanceTest.java
  backend/src/test/java/com/jujeol/drink/acceptance/DrinkAcceptanceTest.java
  backend/src/test/java/com/jujeol/drink/domain/repository/DrinkRepositoryTest.java
  backend/src/test/java/com/jujeol/drink/domain/repository/ReviewRepositoryTest.java
  backend/src/test/java/com/jujeol/member/domain/MemberInfoRepositoryTest.java
  backend/src/test/java/com/jujeol/member/domain/PreferenceRepositoryTest.java
Labels: 🔥 백엔드

#161 refactor: TestDataLoader에 의존적인 테스트 리팩토링
  backend/src/main/java/com/jujeol/drink/domain/repository/DrinkRepository.java
  backend/src/main/java/com/jujeol/drink/ui/DrinkController.java
  backend/src/main/java/com/jujeol/member/application/LoginService.java
  backend/src/main/java/com/jujeol/member/application/SocialClient.java
  backend/src/main/java/com/jujeol/member/infrastructure/kakao/KakaoClient.java
  backend/src/test/java/com/jujeol/AcceptanceTest.java
  backend/src/test/java/com/jujeol/RequestBuilder.java
  backend/src/test/java/com/jujeol/TestDataLoader.java
  backend/src/test/java/com/jujeol/admin/AdminDrinkRequestContainer.java
  backend/src/test/java/com/jujeol/admin/acceptance/AdminAcceptanceTest.java
  backend/src/test/java/com/jujeol/admin/acceptance/AdminAcceptanceTool.java
  backend/src/test/java/com/jujeol/drink/DrinkTestContainer.java
  backend/src/test/java/com/jujeol/drink/acceptance/CategoryAcceptanceTest.java
  backend/src/test/java/com/jujeol/drink/acceptance/CategoryAcceptanceTool.java
  backend/src/test/java/com/jujeol/drink/acceptance/DrinkAcceptanceTest.java
  backend/src/test/java/com/jujeol/drink/acceptance/DrinkAcceptanceTool.java
  backend/src/test/java/com/jujeol/drink/acceptance/ReviewAcceptanceTest.java
  backend/src/test/java/com/jujeol/drink/acceptance/ReviewAcceptanceTool.java
  backend/src/test/java/com/jujeol/member/acceptance/LoginAcceptanceTest.java
  backend/src/test/java/com/jujeol/member/acceptance/MemberAcceptanceTest.java
  backend/src/test/java/com/jujeol/member/acceptance/MemberAcceptanceTool.java
  backend/src/test/java/com/jujeol/member/acceptance/MemberInfoAcceptanceTest.java
  backend/src/test/java/com/jujeol/member/fixture/TestMember.java
  backend/src/test/java/com/jujeol/member/fixture/TestSocialLoginFactory.java
Labels: 🔥 백엔드

#155 feat: 깃헙 액션을 위한 workflow.yml 파일 설정
  .github/workflows/front-dev-deploy.yml
Labels: 🏗인프라, 👩‍💻 프론트

#170 feat: githup action test
  README.md
Labels: 👩‍💻 프론트

#166 chore: 프론트엔드 빌드 환경설정
  frontend/env/.env.prod
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/snowpack.config.mjs
  frontend/src/assets/jujeol-promotion-cheers.png
Labels: ⚙️ 설정⚒, 👩‍💻 프론트

#178 fix: homepage 형식 변경에 따른 테스트 코드 변경
  frontend/src/pages/HomePage/test.tsx
Labels: 🍻 테스트, 🐞 버그, 👩‍💻 프론트

#180 fix: css import 오류 수정
  frontend/src/components/Modal/Modal.styles.ts
  frontend/src/styles/Flex.ts
Labels: 🐞 버그, 👩‍💻 프론트

#183 fix: css import 방식 변경
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Card/PersonalReviewCard.styles.ts
  frontend/src/components/Card/ReviewCard.styles.ts
Labels: 🐞 버그, 👩‍💻 프론트

#184 fix: css import 오류 수정
  frontend/src/components/Modal/Modal.styles.ts
  frontend/src/styles/Flex.ts
Labels: 🐞 버그, 👩‍💻 프론트

#186 chore: 프론트 PR 시 빌드 테스트 추가, gitignore에 .env 추가, dev, prod 환경변수 변경
  .github/workflows/front-build-test.yml
  .github/workflows/front-prod-deploy.yml
  frontend/.env
  frontend/.gitignore
  frontend/env/.env.development
  frontend/env/.env.prod
Labels: ⚙️ 설정⚒, 🏗인프라, 👩‍💻 프론트

#179 feat: 상세페이지 선호도 평균 추가 및 리뷰 무한스크롤 구현
  frontend/snowpack.config.mjs
  frontend/src/GlobalStyle.tsx
  frontend/src/apis/requests.ts
  frontend/src/components/Card/ReviewCard.tsx
  frontend/src/components/Modal/ModalProvider.tsx
  frontend/src/components/RangeWithIcons/RangeWithIcons.tsx
  frontend/src/components/Review/Review.tsx
  frontend/src/components/Review/ReviewCreateForm.tsx
  frontend/src/components/Review/ReviewEditForm.tsx
  frontend/src/mocks/drinksDetail.ts
  frontend/src/mocks/drinksReviews.ts
  frontend/src/mocks/mockTestFunction.ts
  frontend/src/pages/DrinksDetailPage/NotAuthorized.test.tsx
  frontend/src/pages/DrinksDetailPage/index.tsx
  frontend/src/pages/DrinksDetailPage/styles.ts
  frontend/src/pages/DrinksDetailPage/test.tsx
Labels: 👩‍💻 프론트, 🕹 기능

#189 feat: 검색페이지 및 검색결과 페이지 마크업 구현
  frontend/src/App.tsx
  frontend/src/GlobalStyle.tsx
  frontend/src/components/@shared/Grid/Grid.ts
  frontend/src/components/@shared/Header/Header.styles.ts
  frontend/src/components/@shared/SearchBar/SearchBar.styles.ts
  frontend/src/components/@shared/SearchBar/SearchBar.tsx
  frontend/src/components/Icons/search.tsx
  frontend/src/components/Tab/Tab.styles.ts
  frontend/src/components/Tab/Tab.tsx
  frontend/src/constants/path.ts
  frontend/src/pages/HomePage/index.tsx
  frontend/src/pages/MyDrinksPage/index.tsx
  frontend/src/pages/MyPage/index.tsx
  frontend/src/pages/MyReviewsPage/index.tsx
  frontend/src/pages/SearchPage/index.tsx
  frontend/src/pages/SearchPage/styles.ts
  frontend/src/pages/SearchResultPage/index.tsx
  frontend/src/pages/SearchResultPage/styles.ts
  frontend/src/styles.ts
Labels: 👩‍💻 프론트, 📱 UI
