Repository woowacourse-teams/2021-jujeol-jujeol, pull requests merged in 2021-09, with the labels that each got.

#345 feat: flyway 적용을 위한 설정 추가
  backend/build.gradle
  backend/src/main/java/com/jujeol/DataLoader.java
  backend/src/main/resources/application-prod.yml
  backend/src/main/resources/application.yml
  backend/src/main/resources/db/migration/prod/V1__init.sql
Labels: 🔥 백엔드, 🏗 인프라

#342 feat: Drink 상세 설명 칼럼 추가 및 관리자 페이지 API 변경
  backend/src/main/java/com/jujeol/DataLoader.java
  backend/src/main/java/com/jujeol/admin/ui/AdminController.java
  backend/src/main/java/com/jujeol/admin/ui/dto/AdminDrinkRequest.java
  backend/src/main/java/com/jujeol/admin/ui/dto/AdminDrinkResponse.java
  backend/src/main/java/com/jujeol/commons/config/P6spySqlLogFormatter.java
  backend/src/main/java/com/jujeol/commons/exception/ExceptionCodeAndDetails.java
  backend/src/main/java/com/jujeol/commons/exception/ExceptionController.java
  backend/src/main/java/com/jujeol/commons/exception/NotFoundErrorCodeException.java
  backend/src/main/java/com/jujeol/commons/interceptor/PathContainer.java
  backend/src/main/java/com/jujeol/drink/drink/application/DrinkService.java
  backend/src/main/java/com/jujeol/drink/drink/application/dto/DrinkDto.java
  backend/src/main/java/com/jujeol/drink/drink/application/dto/DrinkRequestDto.java
  backend/src/main/java/com/jujeol/drink/drink/domain/Description.java
  backend/src/main/java/com/jujeol/drink/drink/domain/Drink.java
  backend/src/main/java/com/jujeol/drink/drink/domain/repository/DrinkRepositoryImpl.java
  backend/src/main/java/com/jujeol/drink/drink/exception/InvalidDescriptionException.java
  backend/src/main/java/com/jujeol/drink/recommend/application/RecommendFactory.java
  backend/src/main/java/com/jujeol/drink/recommend/domain/RecommendForMember.java
  backend/src/main/resources/db/migration/prod/V2__drink_add_description.sql
  backend/src/test/java/com/jujeol/RequestBuilder.java
  backend/src/test/java/com/jujeol/admin/acceptance/AdminAcceptanceTest.java
  backend/src/test/java/com/jujeol/admin/acceptance/AdminAcceptanceTool.java
  backend/src/test/java/com/jujeol/drink/DrinkTestContainer.java
  backend/src/test/java/com/jujeol/drink/acceptance/DrinkAcceptanceTool.java
  backend/src/test/java/com/jujeol/drink/domain/repository/DrinkRepositoryTest.java
  backend/src/test/java/com/jujeol/drink/drink/domain/DescriptionTest.java
  backend/src/test/java/com/jujeol/member/acceptance/LoginAcceptanceTest.java
  backend/src/test/java/com/jujeol/member/acceptance/MemberAcceptanceTest.java
  backend/src/test/java/com/jujeol/member/acceptance/MemberInfoAcceptanceTest.java
  backend/src/test/java/com/jujeol/member/domain/BiographyTest.java
  backend/src/test/java/com/jujeol/member/domain/MemberInfoRepositoryTest.java
  backend/src/test/java/com/jujeol/member/domain/MemberRepositoryTest.java
  backend/src/test/java/com/jujeol/member/domain/NicknameTest.java
  backend/src/test/java/com/jujeol/member/domain/PreferenceRepositoryTest.java
  backend/src/test/java/com/jujeol/member/fixture/TestMember.java
  backend/src/test/java/com/jujeol/member/fixture/TestSocialLoginFactory.java
  backend/src/test/java/com/jujeol/member/fixture/TestsCheersExpressionRepository.java
  backend/src/test/java/com/jujeol/review/domain/ReviewContentTest.java
  backend/src/test/java/com/jujeol/review/domain/repository/ReviewRepositoryTest.java
  backend/src/test/java/com/jujeol/testdatabase/QueryCounter.java
  backend/src/test/java/com/jujeol/testdatabase/QueryResult.java
Labels: 🕹 기능, 🔥 백엔드

#347 feat: 비동기 로깅 적용
  backend/src/main/java/com/jujeol/drink/drink/application/DrinkService.java
  backend/src/main/java/com/jujeol/drink/drink/ui/DrinkController.java
  backend/src/main/resources/logback-access.xml
  backend/src/main/resources/logback-spring.xml
Labels: 🔥 백엔드

#352 feat: 관리자도구 상세정보 입력기능 추가
  backend/build.gradle
  backend/src/main/resources/static/admin/bootstrap/bootstrap.min.css
  backend/src/main/resources/static/admin/css/dashboard.css
  backend/src/main/resources/static/admin/html/index.html
  backend/src/main/resources/static/admin/js/admin.js
  backend/src/main/resources/static/admin/js/drinks/component/drinkInsertModalRow.js
  backend/src/main/resources/static/admin/js/drinks/component/drinkTableColumns.js
  backend/src/main/resources/static/admin/js/drinks/dto/DrinkRequest.js
  backend/src/main/resources/static/admin/js/drinks/handler/HandlerDrinkBatchInsert.js
  backend/src/main/resources/static/admin/js/drinks/model/Drink.js
  backend/src/main/resources/static/admin/js/drinks/view/drinkTable.js
  backend/src/main/resources/static/admin/js/utils/methodFetches.js
  backend/src/main/resources/static/admin/js/utils/validator.js
Labels: 🕹 기능, 🔥 백엔드

#354 feat: 피드백 반영
  backend/src/main/java/com/jujeol/drink/drink/domain/ImageFilePath.java
  backend/src/main/java/com/jujeol/drink/drink/ui/dto/DrinkResponse.java
  backend/src/main/java/com/jujeol/drink/drink/ui/dto/DrinkSimpleResponse.java
  backend/src/main/resources/db/migration/prod/V3__drink_add_imageFilePath.sql
Labels: 🕹 기능, 🔥 백엔드

#351 feat: snackbar 구현
  frontend/public/index.html
  frontend/src/App.tsx
  frontend/src/GlobalStyle.tsx
  frontend/src/components/@shared/Snackbar/Snackbar.styles.ts
  frontend/src/components/@shared/Snackbar/Snackbar.tsx
  frontend/src/components/@shared/Snackbar/SnackbarProvider.tsx
  frontend/src/constants/index.ts
  frontend/src/constants/messages.ts
  frontend/src/constants/portal.ts
Labels: 🕹 기능, 🌈 프론트, 📱유아이

#356 fix: 카테고리 및 선호도 버그 수정
  backend/src/main/java/com/jujeol/drink/drink/application/DrinkService.java
  backend/src/main/java/com/jujeol/drink/drink/domain/repository/DrinkRepository.java
  backend/src/main/java/com/jujeol/drink/drink/ui/DrinkController.java
  backend/src/main/java/com/jujeol/drink/recommend/domain/RecommendForMember.java
  frontend/package-lock.json
  frontend/src/components/Item/CardItem.tsx
  frontend/src/components/Item/ListItem.styles.ts
  frontend/src/components/Item/ListItem.tsx
  frontend/src/constants/category.ts
  frontend/src/pages/DrinksDetailPage/index.tsx
  frontend/src/pages/HomePage/DrinkListSection.tsx
  frontend/src/pages/HomePage/config.ts
  frontend/src/pages/HomePage/index.tsx
  frontend/src/pages/HomePage/styles.ts
  frontend/src/types.d.ts
  frontend/src/utils/idGenerator.ts
  frontend/src/utils/random.ts
Labels: 🔥 백엔드, 🐞 버그

#357 feat: 프론트엔드 성능 최적화
  frontend/public/index.html
  frontend/src/App.tsx
  frontend/src/components/Banner/Banner.styles.ts
Labels: ⚙️ 설정, 🌈 프론트, ⚒ 리팩토링

#359 feat: 관리자 페이지 이미지 리사이징과 업로드
  backend/build.gradle
  backend/src/main/java/com/jujeol/admin/ui/AdminController.java
  backend/src/main/java/com/jujeol/admin/ui/dto/AdminDrinkRequest.java
  backend/src/main/java/com/jujeol/admin/ui/dto/AdminDrinkResponse.java
  backend/src/main/java/com/jujeol/aws/config/S3Config.java
  backend/src/main/java/com/jujeol/aws/exception/ImageFileResizingException.java
  backend/src/main/java/com/jujeol/aws/infrastructure/S3Uploader.java
  backend/src/main/java/com/jujeol/aws/service/ImageResizer.java
  backend/src/main/java/com/jujeol/aws/service/ImageResizerImpl.java
  backend/src/main/java/com/jujeol/aws/service/ImageService.java
  backend/src/main/java/com/jujeol/commons/aop/LogAop.java
  backend/src/main/java/com/jujeol/commons/exception/ExceptionCodeAndDetails.java
  backend/src/main/java/com/jujeol/drink/drink/application/DrinkService.java
  backend/src/main/java/com/jujeol/drink/drink/application/dto/DrinkDto.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-prod.yml
  backend/src/main/resources/application.yml
  backend/src/main/resources/static/admin/js/drinks/component/drinkInsertModalRow.js
  backend/src/main/resources/static/admin/js/drinks/dto/DrinkRequest.js
  backend/src/main/resources/static/admin/js/drinks/handler/HandlerDrinkBatchInsert.js
  backend/src/main/resources/static/admin/js/drinks/view/drinkTable.js
  backend/src/main/resources/static/admin/js/utils/methodFetches.js
  backend/src/test/java/com/jujeol/admin/acceptance/AdminAcceptanceTest.java
  backend/src/test/java/com/jujeol/admin/acceptance/AdminAcceptanceTool.java
  backend/src/test/java/com/jujeol/drink/DrinkTestContainer.java
  backend/src/test/java/com/jujeol/drink/acceptance/DrinkAcceptanceTest.java
  backend/src/test/java/com/jujeol/drink/drink/application/dto/SearchDtoTest.java
  backend/src/test/java/com/jujeol/member/acceptance/MemberAcceptanceTest.java
  backend/src/test/resources/static/testimage.png
Labels: 🕹 기능, 🔥 백엔드, 🏗 인프라

#364 fix: 이미지 경로 수정
  backend/src/main/java/com/jujeol/DataLoader.java
Labels: 🔥 백엔드, 🐞 버그

#362 feat: 닉네임 수정 기능 구현
  frontend/src/apis/requests.ts
  frontend/src/components/@shared/Icons/DizzyEmojiColorIcon.tsx
  frontend/src/components/@shared/Icons/DizzyEmojiIcon.tsx
  frontend/src/components/@shared/Icons/EditIcon.tsx
  frontend/src/components/@shared/Icons/ExcitedEmojiColorIcon.tsx
  frontend/src/components/@shared/Icons/ExcitedEmojiIcon.tsx
  frontend/src/components/@shared/Icons/LoveEmojiColorIcon.tsx
  frontend/src/components/@shared/Icons/LoveEmojiIcon.tsx
  frontend/src/components/@shared/Icons/MakgeolliColorIcon.tsx
  frontend/src/components/@shared/Icons/MakgeolliIcon.tsx
  frontend/src/components/@shared/Icons/SmileEmojiColorIcon.tsx
  frontend/src/components/@shared/Icons/SmileEmojiIcon.tsx
  frontend/src/components/Profile/EditModalForm.styles.ts
  frontend/src/components/Profile/EditModalForm.tsx
  frontend/src/components/Profile/Profile.styles.ts
  frontend/src/components/Profile/Profile.tsx
Labels: 🕹 기능, 🌈 프론트, 📱유아이

#366 fix: imageURL 변경 누락 부분 수정
  frontend/src/pages/MyPage/NoPreference.tsx
Labels: 🌈 프론트, 🐞 버그

#371 feat: 변경된 api 문서화 적용
  backend/src/docs/asciidoc/drink.adoc
  backend/src/test/java/com/jujeol/drink/acceptance/DrinkAcceptanceTest.java
Labels: 📋 문서, 🔥 백엔드
