Repository woowacourse-teams/2021-jujeol-jujeol, pull requests merged in 2021-12, with the labels that each got.

#612 feat: 프론트엔드 빌드 설정 추가
  .github/workflows/front-dev-deploy.yml
  .github/workflows/front-prod-deploy.yml
Labels: 🏗 인프라, 🎯 배포

#620 docs: Hibernate 오타 수정
  README.md
Labels: 📋 문서, ⚒ 리팩토링

#622 feat: log4j 취약점 버전 이슈 해결
  backend/build.gradle
Labels: 🔥 백엔드, 🚨 이슈

#619 chore: prod API 주소변경
  frontend/env/.env.prod
Labels: ⚙️ 설정, 🌈 프론트

#624 chore: 도메인 주소 임시 변경
  frontend/env/.env.prod
Labels: 🌈 프론트, 🎯 배포

#626 chore: 배너 이미지 url 변경 및 og:url 변경
  frontend/public/index.html
  frontend/src/pages/HomePage/config.ts
Labels: 🌈 프론트, 🎯 배포
